#include "device/serial/serial.h"
#include "stm32f7xx_hal.h"
#include <stdio.h>
#include <stdarg.h>
#include "rk043fn48h.h"
#include "fonts.h"
#include "device/display/display.h"
#include "board/stm32f7/configs.h"

// Use the UART handle generated by STM32CubeMX
extern DCMI_HandleTypeDef hdcmi;
extern LTDC_HandleTypeDef hltdc;

static void display_init(void)
{
    HAL_LTDC_SetAddress(&hltdc, FRAME_BUFFER + 0x100000,
                        LTDC_LAYER_1);
    HAL_LTDC_Reload(&hltdc, LTDC_RELOAD_IMMEDIATE);
}

static void display_deinit(void)
{
    HAL_LTDC_DeInit(&hltdc);
}

static void display_reset(void)
{
    // No config
}

#define LCD_FRAMEBUFFER ((uint16_t *)FRAME_BUFFER + 0x100000)
#define LCD_WIDTH 480
#define LCD_HEIGHT 272

static void display_clear(displayColor color)
{
    for (uint32_t i = 0; i < (LCD_WIDTH * LCD_HEIGHT); i++)
    {
        LCD_FRAMEBUFFER[i] = color;
    }

    // Reset to the default array.
    HAL_LTDC_SetAddress(&hltdc, LCD_FRAMEBUFFER,
                        LTDC_LAYER_1);
}

static void display_show(Image *inImg)
{

    switch (inImg->format)
    {
    case IMAGE_FORMAT_RGB888:
    {
        HAL_LTDC_SetPixelFormat(&hltdc, LTDC_PIXEL_FORMAT_RGB888, LTDC_LAYER_1);
        break;
    }
    case IMAGE_FORMAT_RGB565:
    {
        HAL_LTDC_SetPixelFormat(&hltdc, LTDC_PIXEL_FORMAT_RGB565, LTDC_LAYER_1);
        break;
    }
    case IMAGE_FORMAT_GRAYSCALE:
    {
        HAL_LTDC_SetPixelFormat(&hltdc, LTDC_PIXEL_FORMAT_L8, LTDC_LAYER_1);
        break;
    }
    default:
    {
        // should not go there
        return;
    }
    }

    HAL_LTDC_SetWindowSize(&hltdc, inImg->width, inImg->height, LTDC_LAYER_1);
    HAL_LTDC_SetAddress(&hltdc, inImg->pixels,
                        LTDC_LAYER_1);
    HAL_LTDC_Reload(&hltdc, LTDC_RELOAD_IMMEDIATE);
}

display_t stm32_ota5180a = {
    .init = display_init,
    .show = display_show,
    .clear = display_clear,
};