#include "serial.h"
#include "stm32f7xx_hal.h"
#include <stdio.h>
#include <stdarg.h>
#include "stm32746g_discovery.h"
#include "stm32746g_discovery_sdram.h"
#include "ov5640.h"
#include "rk043fn48h.h"
#include "fonts.h"
#include "camera.h"
#include "configs.h"

// Use the UART handle generated by STM32CubeMX
extern UART_HandleTypeDef huart1;
extern DCMI_HandleTypeDef hdcmi;
extern DMA_HandleTypeDef hdma_dcmi;
extern DMA2D_HandleTypeDef hdma2d;
extern LTDC_HandleTypeDef hltdc;

static volatile uint32_t start_the_camera_capture = 0;
typedef enum
{
    CAMERA_OK = 0x00,
    CAMERA_ERROR = 0x01,
    CAMERA_TIMEOUT = 0x02,
    CAMERA_NOT_DETECTED = 0x03,
    CAMERA_NOT_SUPPORTED = 0x04
} Camera_StatusTypeDef;

static RCC_PeriphCLKInitTypeDef periph_clk_init_struct;
CAMERA_DrvTypeDef *camera_driv;
/* Camera module I2C HW address */
static uint32_t CameraHwAddress;
/* Image size */
uint32_t Im_size = 0;

/* Camera resolution is QWVGA (480x272) */
static uint32_t CameraResX = QVGA_RES_X;
static uint32_t CameraResY = QVGA_RES_Y;
static uint32_t LcdResX = WQVGA_RES_X; /* QWVGA landscape */
static uint32_t LcdResY = WQVGA_RES_Y;

static uint32_t offset_cam = 0;
static uint32_t offset_lcd = 0;

__IO uint16_t pBuffer[QVGA_RES_X * QVGA_RES_Y];
HAL_StatusTypeDef hal_status = HAL_OK;

uint8_t CAMERA_Init(uint32_t Resolution) /*Camera initialization*/
{
    uint8_t status = CAMERA_ERROR;
    /* Read ID of Camera module via I2C */
    if (ov5640_ReadID(CAMERA_I2C_ADDRESS) == OV5640_ID)
    {
        camera_driv = &ov5640_drv;
        /* Initialize the camera driver structure */
        CameraHwAddress = CAMERA_I2C_ADDRESS;
        camera_driv->Init(CameraHwAddress, Resolution);
        HAL_DCMI_DisableCROP(&hdcmi);
        HAL_Delay(500);

        status = CAMERA_OK; /* Return CAMERA_OK status */
    }
    else
    {
        status = CAMERA_NOT_SUPPORTED; /* Return CAMERA_NOT_SUPPORTED status */
    }
    return status;
}

/**
 * @brief  CANERA power up
 * @retval None
 */
void CAMERA_PwrUp(void)
{
    GPIO_InitTypeDef gpio_init_structure;

    /* Enable GPIO clock */
    __HAL_RCC_GPIOH_CLK_ENABLE();

    /*** Configure the GPIO ***/
    /* Configure DCMI GPIO as alternate function */
    gpio_init_structure.Pin = GPIO_PIN_13;
    gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init_structure.Pull = GPIO_NOPULL;
    gpio_init_structure.Speed = GPIO_SPEED_HIGH;
    HAL_GPIO_Init(GPIOH, &gpio_init_structure);

    /* De-assert the camera POWER_DOWN pin (active high) */
    HAL_GPIO_WritePin(GPIOH, GPIO_PIN_13, GPIO_PIN_RESET);

    HAL_Delay(3); /* POWER_DOWN de-asserted during 3ms */
}

/**
 * @brief  CAMERA power down
 * @retval None
 */
void CAMERA_PwrDown(void)
{
    GPIO_InitTypeDef gpio_init_structure;

    /* Enable GPIO clock */
    __HAL_RCC_GPIOH_CLK_ENABLE();

    /*** Configure the GPIO ***/
    /* Configure DCMI GPIO as alternate function */
    gpio_init_structure.Pin = GPIO_PIN_13;
    gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init_structure.Pull = GPIO_NOPULL;
    gpio_init_structure.Speed = GPIO_SPEED_HIGH;
    HAL_GPIO_Init(GPIOH, &gpio_init_structure);

    /* Assert the camera POWER_DOWN pin (active high) */
    HAL_GPIO_WritePin(GPIOH, GPIO_PIN_13, GPIO_PIN_SET);
}

/**
 * @brief  Converts a line to an ARGB8888 pixel format.
 * @param  pSrc: Pointer to source buffer
 * @param  pDst: Output color
 * @param  ColorMode: Input color mode
 * @retval None
 */
static void LCD_LL_ConvertLineToARGB8888(void *pSrc, void *pDst)
{
    /* Enable DMA2D clock */
    __HAL_RCC_DMA2D_CLK_ENABLE();

    /* Configure the DMA2D Mode, Color Mode and output offset */
    hdma2d.Init.Mode = DMA2D_M2M_PFC;
    hdma2d.Init.ColorMode = DMA2D_OUTPUT_RGB565; // DMA2D_OUTPUT_ARGB8888; /* Output color out of PFC */
    hdma2d.Init.OutputOffset = 0;
    // hdma2d.Init.AlphaInverted = DMA2D_REGULAR_ALPHA;  /* No Output Alpha Inversion*/
    // hdma2d.Init.RedBlueSwap   = DMA2D_RB_REGULAR;     /* No Output Red & Blue swap */

    // DMA2D_INPUT_ARGB8888        0x00000000U  /*!< ARGB8888 color mode */
    // DMA2D_INPUT_RGB888          0x00000001U  /*!< RGB888 color mode   */
    // DMA2D_INPUT_RGB565          0x00000002U  /*!< RGB565 color mode   */
    // DMA2D_INPUT_ARGB1555        0x00000003U  /*!< ARGB1555 color mode */
    // DMA2D_INPUT_ARGB4444        0x00000004U  /*!< ARGB4444 color mode */
    // DMA2D_INPUT_L8              0x00000005U  /*!< L8 color mode       */
    // DMA2D_INPUT_AL44            0x00000006U  /*!< AL44 color mode     */
    // DMA2D_INPUT_AL88            0x00000007U  /*!< AL88 color mode     */
    // DMA2D_INPUT_L4              0x00000008U  /*!< L4 color mode       */
    // DMA2D_INPUT_A8              0x00000009U  /*!< A8 color mode       */
    // DMA2D_INPUT_A4              0x0000000AU  /*!< A4 color mode       */

    /* Foreground Configuration */
    hdma2d.LayerCfg[1].AlphaMode = DMA2D_NO_MODIF_ALPHA;
    hdma2d.LayerCfg[1].InputAlpha = 0xFF; /* fully opaque */
    hdma2d.LayerCfg[1].InputColorMode = DMA2D_INPUT_RGB565;
    hdma2d.LayerCfg[1].InputOffset = 0;
    // hdma2d.LayerCfg[1].RedBlueSwap = DMA2D_RB_REGULAR; /* No ForeGround Red/Blue swap */
    // hdma2d.LayerCfg[1].AlphaInverted = DMA2D_REGULAR_ALPHA; /* No ForeGround Alpha inversion */

    hdma2d.Instance = DMA2D;

    /* DMA2D Initialization */
    if (HAL_DMA2D_Init(&hdma2d) == HAL_OK)
    {
        if (HAL_DMA2D_ConfigLayer(&hdma2d, 1) == HAL_OK)
        {
            if (HAL_DMA2D_Start(&hdma2d, (uint32_t)pSrc, (uint32_t)pDst, CameraResX, 1) == HAL_OK)
            {
                /* Polling For DMA transfer */
                HAL_DMA2D_PollForTransfer(&hdma2d, 10);
            }
        }
    }
    else
    {
        while (1)
            ;
    }
}

/**
 * @brief  Camera line event callback
 * @param  None
 * @retval None
 */
// void HAL_DCMI_FrameEventCallback(DCMI_HandleTypeDef *hdcmi)
//{
//	if (offset_lcd == 0) // ASSUMPTION Camera resolution is lower than LCD resolution
//	{
//		/* If Camera resolution is lower than LCD resolution, set display in the middle of the screen */
//		offset_lcd =   ((((LcdResY - CameraResY) / 2) * LcdResX)   /* Middle of the screen on Y axis */
//				+   ((LcdResX - CameraResX) / 2))             /* Middle of the screen on X axis */
//     				  * sizeof(uint32_t);
//	}
//
//	for(uint32_t camera_line_nb = 0; camera_line_nb < CameraResY; camera_line_nb++)
//	{
////		LCD_LL_ConvertLineToARGB8888((uint32_t *)(CAMERA_FRAME_BUFFER + offset_cam),
////				(uint32_t *)(LCD_FRAME_BUFFER + offset_lcd));
//
//		for (uint32_t ncol=0; ncol<CameraResX; ncol ++){
//			uint32_t val = (CAMERA_FRAME_BUFFER + offset_cam+4*ncol);
//			*(__IO uint32_t*)(4*ncol+LCD_FRAME_BUFFER) = val;
//		}
//
//		offset_cam  = offset_cam + (CameraResX * sizeof(uint16_t));
//		offset_lcd  = offset_lcd + (LcdResX * sizeof(uint32_t));
//	}
//}

static void test_ConvertLineRGB565ToARGB8888()
{
    // white/magenta test color pattern
    uint32_t offset_cam = 0;
    uint32_t offset_lcd = 0;

    for (uint32_t pos = 0; pos < LcdResX * LcdResY / 2; pos++)
    {
        uint32_t val = LCD_RGB565_COLOR_WHITE << 16 | LCD_RGB565_COLOR_DARKMAGENTA;
        *(__IO uint32_t *)(4 * pos + CAMERA_FRAME_BUFFER) = val;
    }

    for (uint32_t camera_line_nb = 0; camera_line_nb < CameraResY; camera_line_nb++)
    {
        LCD_LL_ConvertLineToARGB8888((uint32_t *)(CAMERA_FRAME_BUFFER + offset_cam),
                                     (uint32_t *)(LCD_FRAME_BUFFER + offset_lcd));

        offset_cam = offset_cam + (CameraResX * sizeof(uint16_t));
        offset_lcd = offset_lcd + (LcdResX * sizeof(uint32_t));
    }
}

/**
 * @brief  On Error Handler on condition TRUE.
 * @param  condition : Can be TRUE or FALSE
 * @retval None
 */
static void OnError_Handler(uint32_t condition)
{
    if (condition)
    {
        BSP_LED_On(LED1);
        while (1)
        {
            ;
        } /* Blocking on error */
    }
}

static void camera_init(void)
{
    CAMERA_PwrDown();
    hal_status = BSP_SDRAM_Init();
    OnError_Handler(hal_status != HAL_OK);

    /*##-3- Camera Initialization and start capture ############################*/
    /* Initialize the Camera in WQVGA mode */
    /* Init camera default resolution and format */
    // hal_status = BSP_CAMERA_Init(CAMERA_R320x240);
    CAMERA_PwrUp();
    HAL_Delay(1000);
    // hal_status = CAMERA_Init(CAMERA_R320x240);
    hal_status = CAMERA_Init(CAMERA_R480x272);

    OnError_Handler(hal_status != HAL_OK);

    HAL_Delay(1000);  // Delay for the camera to output correct data
    Im_size = 0x9600; // size=320*240*2/4
    Im_size = 0xff00; // size=480*272*2/4

    /*##-4- Camera Continuous capture start in QVGA resolution ############################*/
    /* Disable unwanted HSYNC (IT_LINE)/VSYNC interrupts */
    __HAL_DCMI_DISABLE_IT(&hdcmi, DCMI_IT_LINE | DCMI_IT_VSYNC);
    //__HAL_DCMI_ENABLE_IT(&hdcmi, DCMI_IT_FRAME);

    /* uncomment the following line in case of snapshot mode */
    // HAL_DCMI_Start_DMA(&hdcmi, DCMI_MODE_SNAPSHOT, (uint32_t)CAMERA_FRAME_BUFFER, Im_size);
    /* uncomment the following line in case of continuous mode */
    // hal_status = HAL_DCMI_Start_DMA(&hdcmi, DCMI_MODE_CONTINUOUS, (uint32_t)CAMERA_FRAME_BUFFER, Im_size);
    // OnError_Handler(hal_status != HAL_OK);

    // LTDC_Init(FRAME_BUFFER, 0, 0, 480, 272);

    //	hal_status = HAL_DCMI_Start_DMA(&hdcmi, DCMI_MODE_SNAPSHOT , (uint32_t)pBuffer, CameraResX * CameraResY/2);
    //	OnError_Handler(hal_status != HAL_OK);

    //	/*##-4- Frame display ############################*/
    //	/* Wait until LCD frame buffer is ready */
    //	while(start_the_camera_capture == 0) {;}
    //
    //	__IO uint16_t uval=0xffff;
    //	for(__IO uint32_t  uwIndex = 0; uwIndex < 64; uwIndex++)
    //	{
    //		uval=pBuffer[uwIndex];
    //		printf("CAM pBuffer[%lu] = %u\n", uwIndex, uval);
    //	}
    //
    //	printf("\n");
}

static void camera_capture(capture_mode_t mode, Image *inImg)
{

    HAL_DCMI_Start_DMA(&hdcmi, mode == CONTINUOUS ? DCMI_MODE_CONTINUOUS : DCMI_MODE_SNAPSHOT, (uint32_t)inImg->pixels_u8, inImg->size / 4);
}

static void camera_stop(void)
{
    HAL_DCMI_Stop(&hdcmi);
}

camera_t stm32_ov5640 = {
    .init = camera_init,
    .capture = camera_capture,
    .stop = camera_stop};