#include "serial.h"
#include "stm32f7xx_hal.h"
#include <stdio.h>
#include <stdarg.h>
#include <assert.h>

// Use the UART handle generated by STM32CubeMX
extern UART_HandleTypeDef huart1;

static void serial_init(void)
{
    // Optional reinitialization
}

/*
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart)
{
    COUNT++;
    if (COUNT > _blockCount)
    {
        HAL_UART_DMAStop(&huart1);
        return;
    }

    if (COUNT < _blockCount)
    {
        HAL_UART_Transmit_DMA(&huart1, base_addr + (uint8_t)(COUNT * _blocksize), _blocksize);
    }
    else
    {
        HAL_UART_Transmit_DMA(&huart1, base_addr + (uint8_t)(COUNT * _blocksize),
                              _lastblocksize);
    }
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    COUNT++;
    if (COUNT > _blockCount)
    {
        HAL_UART_DMAStop(&huart1);
        return;
    }

    if (COUNT < _blockCount)
    {
        HAL_UART_Receive_DMA(&huart1, base_addr + (uint8_t)(COUNT * _blocksize), _blocksize);
    }
    else
    {
        HAL_UART_Receive_DMA(&huart1, base_addr + (uint8_t)(COUNT * _blocksize),
                             _lastblocksize);
    }
}

static void serial_capture_dma(Image *img)
{
    COUNT = 0;
    base_addr = img->pixels_u8;
    uint8_t request_start_sequence[3] = "STR";

    if (img->size < 65536)
        _blocksize = img->size;

    _blockCount = img->size / _blocksize;
    _lastblocksize = (uint16_t)(img->size % _blocksize);

    HAL_UART_Transmit(&huart1, request_start_sequence, 3, HAL_MAX_DELAY);
    HAL_Delay(1);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->width), sizeof(uint16_t), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->height), sizeof(uint16_t),
                      HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->format), sizeof(uint8_t),
                      HAL_MAX_DELAY);
    HAL_Delay(200);

    int ret = HAL_UART_Receive_DMA(&huart1, img->pixels_u8, _blocksize);

    ret = ret + 1;
}

static void serial_send_dma(Image *img)
{
    COUNT = 0;
    base_addr = img->pixels_u8;
    uint8_t request_start_sequence[3] = "STW";

    if (img->size < 65536)
        _blocksize = img->size;

    _blockCount = img->size / _blocksize;
    _lastblocksize = (uint16_t)(img->size % _blocksize);

    HAL_UART_Transmit(&huart1, request_start_sequence, 3, HAL_MAX_DELAY);
    HAL_Delay(1);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->width), sizeof(uint16_t), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->height), sizeof(uint16_t),
                      HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->format), sizeof(uint8_t),
                      HAL_MAX_DELAY);

    HAL_UART_Transmit_DMA(&huart1, img->pixels_u8, _blocksize);
}

*/

#define UART_BLOCK_SIZE_MAX 65535
#define UART_CMD_CAPTURE "STR"
#define UART_CMD_SEND "STW"

static void serial_capture(Image *img)
{
    uint8_t request_start_sequence[3] = "STR";
    assert(img != NULL);
    assert(img->pixels != NULL);

    // Calculate block parameters
    uint16_t blockSize = ((img->size * img->depth) < UART_BLOCK_SIZE_MAX) ? (img->size * img->depth) : UART_BLOCK_SIZE_MAX;
    uint32_t blockCount = (img->size * img->depth) / blockSize;
    uint16_t lastBlockSize = (img->size * img->depth) % blockSize;

    // Send capture request header
    HAL_UART_Transmit(&huart1, request_start_sequence, 3, HAL_MAX_DELAY);
    HAL_Delay(1); // Optional small delay

    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->width), sizeof(img->width), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->height), sizeof(img->height), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->format), sizeof(img->format), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->depth), sizeof(img->depth), HAL_MAX_DELAY);

    // Receive image data in blocks
    uint8_t *pixelPtr = img->pixels;
    for (uint32_t i = 0; i < blockCount; i++)
    {
        HAL_UART_Receive(&huart1, pixelPtr, blockSize, HAL_MAX_DELAY);
        pixelPtr += blockSize;
    }

    // Receive remaining bytes
    if (lastBlockSize > 0)
    {
        HAL_UART_Receive(&huart1, pixelPtr, lastBlockSize, HAL_MAX_DELAY);
    }
}

static void serial_send(const Image *img)
{
    assert(img != NULL);
    assert(img->pixels != NULL);
    uint8_t request_start_sequence[3] = "STW";
    // Calculate block transmission parameters
    uint16_t blockSize = ((img->size * img->depth) < UART_BLOCK_SIZE_MAX) ? (img->size * img->depth) : UART_BLOCK_SIZE_MAX;
    uint32_t blockCount = (img->size * img->depth) / blockSize;
    uint16_t lastBlockSize = (img->size * img->depth) % blockSize;

    // Step 1: Send command header
    HAL_UART_Transmit(&huart1, request_start_sequence, 3, HAL_MAX_DELAY);
    HAL_Delay(1); // Give receiver time to prepare

    // Step 2: Send image metadata

    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->width), sizeof(img->width), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->height), sizeof(img->height), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->format), sizeof(img->format), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->depth), sizeof(img->depth), HAL_MAX_DELAY);
    HAL_Delay(200); // Allow receiver to process metadata

    // Step 3: Send image pixel data in blocks
    const uint8_t *pixelPtr = img->pixels;
    for (uint32_t i = 0; i < blockCount; i++)
    {
        HAL_UART_Transmit(&huart1, pixelPtr, blockSize, HAL_MAX_DELAY);
        pixelPtr += blockSize;
        HAL_Delay(1); // <-- 1-2ms delay between blocks
    }

    // Step 4: Send any remaining bytes
    if (lastBlockSize > 0)
    {
        HAL_UART_Transmit(&huart1, pixelPtr, lastBlockSize, HAL_MAX_DELAY);
        HAL_Delay(1); // <-- 1-2ms delay between blocks
    }
}

/*
static void serial_capture(Image *img)
{

    uint8_t request_start_sequence[3] = "STR";

    uint16_t _blocksize = 65535, _lastblocksize = 0;
    uint32_t i = 0, _blockCount = 0;

    uint16_t sizear[3] = {img->width, img->height, img->format};

    if (img->size < 65536)
        _blocksize = img->size;

    _blockCount = img->size / _blocksize;
    _lastblocksize = (uint16_t)(img->size % _blocksize);

    HAL_UART_Transmit(&huart1, request_start_sequence, 3, HAL_MAX_DELAY);
    HAL_Delay(1);

    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->width), sizeof(uint16_t), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->height), sizeof(uint16_t),
                      HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->format), sizeof(uint16_t),
                      HAL_MAX_DELAY);

    for (i = 0; i < _blockCount; i++)
        HAL_UART_Receive(&huart1, img->pixels + (i * _blocksize), _blocksize,
                         HAL_MAX_DELAY);

    if (_lastblocksize)
        HAL_UART_Receive(&huart1, img->pixels + (i * _blocksize),
                         _lastblocksize, HAL_MAX_DELAY);

    return;
}

static void serial_send(const Image *img)
{
    uint8_t request_start_sequence[3] = "STW";

    uint16_t _blocksize = 65535, _lastblocksize = 0;
    uint32_t i = 0, _blockCount = 0;

    if (img->size < 65536)
        _blocksize = img->size;

    _blockCount = img->size / _blocksize;
    _lastblocksize = (uint16_t)(img->size % _blocksize);

    HAL_UART_Transmit(&huart1, request_start_sequence, 3, HAL_MAX_DELAY);
    HAL_Delay(1);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->width), sizeof(uint16_t), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->height), sizeof(uint16_t),
                      HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&img->format), sizeof(uint8_t),
                      HAL_MAX_DELAY);
    HAL_Delay(200);
    for (i = 0; i < _blockCount; i++)
        HAL_UART_Transmit(&huart1, img->pixels + (i * _blocksize), _blocksize,
                          HAL_MAX_DELAY);

    if (_lastblocksize)
        HAL_UART_Transmit(&huart1, img->pixels + (i * _blocksize),
                          _lastblocksize, HAL_MAX_DELAY);
}

int _write(int file, char *ptr, int len)
{
    for (int i = 0; i < len; i++)
    {
        HAL_UART_Transmit(&huart1, (uint8_t *)&ptr[i], 1, HAL_MAX_DELAY);
    }
    return len;
}
*/

// Define the object
serial_t stm32_uart = {
    .init = serial_init,
    .capture = serial_capture,
    .send = serial_send};