// SPDX-License-Identifier: MIT
// Copyright (c) 2025 EmbedDIP

#include <embedDIP_configs.h>

#ifdef DEVICE_STM32_UART

    #include "core/error.h"
    #include "device/serial/serial.h"

    #include <stdarg.h>
    #include <stdio.h>

    #include "stm32f7xx_hal.h"

    // Validation macros to replace assert()
    #define CHECK_NULL_INT(ptr)                                                                    \
        do {                                                                                       \
            if (!(ptr))                                                                            \
                return EMBEDDIP_ERROR_NULL_PTR;                                                    \
        } while (0)

    #define CHECK_CONDITION_INT(cond)                                                              \
        do {                                                                                       \
            if (!(cond))                                                                           \
                return EMBEDDIP_ERROR_INVALID_ARG;                                                 \
        } while (0)

// Use the UART handle generated by STM32CubeMX
extern UART_HandleTypeDef huart1;

static int serial_init(void)
{
    // Optional reinitialization
    return EMBEDDIP_OK;
}

static int serial_flush(void)
{
    __HAL_UART_SEND_REQ(&huart1, UART_RXDATA_FLUSH_REQUEST);
    return EMBEDDIP_OK;
}

    #define UART_BLOCK_SIZE_MAX 65535
    #define UART_CMD_CAPTURE "STR"
    #define UART_CMD_SEND "STW"

volatile bool tx_flag, rx_flag = false;

void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart)
{
    (void)huart;
    tx_flag = true;
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    (void)huart;
    rx_flag = true;
}

static int serial_capture(Image *img)
{
    uint8_t request_start_sequence[3] = "STR";
    CHECK_NULL_INT(img);
    CHECK_NULL_INT(img->pixels);

    // Abort any ongoing transfers from previous session
    HAL_UART_Abort(&huart1);

    // Clear all UART error flags
    __HAL_UART_CLEAR_FLAG(&huart1,
                          UART_CLEAR_OREF | UART_CLEAR_NEF | UART_CLEAR_FEF | UART_CLEAR_PEF);

    // Flush RX buffer
    __HAL_UART_SEND_REQ(&huart1, UART_RXDATA_FLUSH_REQUEST);

    // Reset UART state to ready
    huart1.RxState = HAL_UART_STATE_READY;
    huart1.gState = HAL_UART_STATE_READY;

    // Calculate block parameters
    uint32_t totalBytes = img->size * img->depth;
    if (totalBytes == 0U) {
        return EMBEDDIP_ERROR_INVALID_SIZE;
    }
    uint16_t blockSize =
        (totalBytes < UART_BLOCK_SIZE_MAX) ? (uint16_t)totalBytes : UART_BLOCK_SIZE_MAX;
    uint32_t blockCount = totalBytes / blockSize;
    uint16_t lastBlockSize = (uint16_t)(totalBytes % blockSize);

    // Send capture request header
    HAL_UART_Transmit(&huart1, request_start_sequence, 3, 5000);
    HAL_Delay(1);  // Optional small delay

    // Send metadata as fixed-size uint32_t to match Python expectations
    uint32_t width_u32 = img->width;
    uint32_t height_u32 = img->height;
    uint32_t format_u32 = (uint32_t)img->format;
    uint32_t depth_u32 = (uint32_t)img->depth;

    HAL_UART_Transmit(&huart1, (uint8_t *)(&width_u32), sizeof(uint32_t), 1000);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&height_u32), sizeof(uint32_t), 1000);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&format_u32), sizeof(uint32_t), 1000);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&depth_u32), sizeof(uint32_t), 1000);

    // Receive image data in blocks with timeout
    uint8_t *pixelPtr = img->pixels;
    HAL_StatusTypeDef status;
    for (uint32_t i = 0; i < blockCount; i++) {
        status =
            HAL_UART_Receive(&huart1, pixelPtr, blockSize, 10000);  // 10 second timeout per block
        if (status != HAL_OK) {
            // Clear errors and return error code
            __HAL_UART_CLEAR_FLAG(&huart1, UART_CLEAR_OREF | UART_CLEAR_NEF | UART_CLEAR_FEF);
            return EMBEDDIP_ERROR_IO_ERROR;
        }
        pixelPtr += blockSize;
    }

    // Receive remaining bytes
    if (lastBlockSize > 0) {
        status = HAL_UART_Receive(&huart1, pixelPtr, lastBlockSize, 10000);
        if (status != HAL_OK) {
            __HAL_UART_CLEAR_FLAG(&huart1, UART_CLEAR_OREF | UART_CLEAR_NEF | UART_CLEAR_FEF);
            return EMBEDDIP_ERROR_IO_ERROR;
        }
    }
    return EMBEDDIP_OK;
}

static int serial_send(const Image *img)
{
    CHECK_NULL_INT(img);
    CHECK_NULL_INT(img->pixels);
    uint8_t request_start_sequence[3] = "STW";
    // Calculate block transmission parameters
    uint32_t totalBytes = img->size * img->depth;
    if (totalBytes == 0U) {
        return EMBEDDIP_ERROR_INVALID_SIZE;
    }
    uint16_t blockSize =
        (totalBytes < UART_BLOCK_SIZE_MAX) ? (uint16_t)totalBytes : UART_BLOCK_SIZE_MAX;
    uint32_t blockCount = totalBytes / blockSize;
    uint16_t lastBlockSize = (uint16_t)(totalBytes % blockSize);

    // Step 1: Send command header
    HAL_UART_Transmit(&huart1, request_start_sequence, 3, HAL_MAX_DELAY);
    HAL_Delay(1);  // Give receiver time to prepare

    // Step 2: Send image metadata as fixed-size uint32_t to match Python expectations
    uint32_t width_u32 = img->width;
    uint32_t height_u32 = img->height;
    // Convert IMAGE_FORMAT_MASK to IMAGE_FORMAT_GRAYSCALE for host compatibility
    uint32_t format_u32 =
        (img->format == IMAGE_FORMAT_MASK) ? IMAGE_FORMAT_GRAYSCALE : (uint32_t)img->format;
    uint32_t depth_u32 = (uint32_t)img->depth;

    HAL_UART_Transmit(&huart1, (uint8_t *)(&width_u32), sizeof(uint32_t), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&height_u32), sizeof(uint32_t), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&format_u32), sizeof(uint32_t), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, (uint8_t *)(&depth_u32), sizeof(uint32_t), HAL_MAX_DELAY);
    HAL_Delay(2);  // Allow receiver to process metadata

    // Step 3: Send image pixel data in blocks
    const uint8_t *pixelPtr = img->pixels;
    for (uint32_t i = 0; i < blockCount; i++) {
        HAL_UART_Transmit(&huart1, pixelPtr, blockSize, HAL_MAX_DELAY);
        pixelPtr += blockSize;
        HAL_Delay(1);  // <-- 1-2ms delay between blocks
    }

    // Step 4: Send any remaining bytes
    if (lastBlockSize > 0) {
        HAL_UART_Transmit(&huart1, pixelPtr, lastBlockSize, HAL_MAX_DELAY);
        HAL_Delay(1);  // <-- 1-2ms delay between blocks
    }
    return EMBEDDIP_OK;
}

static int serial_send_jpeg(const Image *img)
{
    CHECK_NULL_INT(img);
    CHECK_NULL_INT(img->pixels);

    const uint8_t header[3] = "STJ";
    HAL_UART_Transmit(&huart1, (uint8_t *)header, sizeof(header), HAL_MAX_DELAY);

    // Send JPEG size (uint32_t)
    HAL_UART_Transmit(&huart1, (uint8_t *)&img->size, sizeof(img->size), HAL_MAX_DELAY);

    // Send JPEG data
    const uint8_t *ptr = img->pixels;
    uint32_t remaining = img->size;

    while (remaining > 0) {
        uint16_t chunk = (remaining > UART_BLOCK_SIZE_MAX) ? UART_BLOCK_SIZE_MAX : remaining;
        HAL_UART_Transmit(&huart1, ptr, chunk, HAL_MAX_DELAY);
        ptr += chunk;
        remaining -= chunk;
    }
    return EMBEDDIP_OK;
}

static int
serial_send_1d(const void *data, uint8_t elem_size, uint32_t length, Serial1DDataType type)
{
    CHECK_NULL_INT(data);
    CHECK_CONDITION_INT(elem_size > 0);
    CHECK_CONDITION_INT(length > 0);

    char header[3] = {'S', 'T', '0' + (char)type};  // e.g., ST1 for histogram
    HAL_UART_Transmit(&huart1, (uint8_t *)header, sizeof(header), HAL_MAX_DELAY);

    // Send metadata: element count and size
    HAL_UART_Transmit(&huart1, (uint8_t *)&length, sizeof(length), HAL_MAX_DELAY);
    HAL_UART_Transmit(&huart1, &elem_size, sizeof(elem_size), HAL_MAX_DELAY);
    HAL_Delay(1);

    // Send data in chunks
    const uint8_t *ptr = (const uint8_t *)data;
    uint32_t remaining = elem_size * length;

    while (remaining > 0) {
        uint16_t chunk = (remaining > UART_BLOCK_SIZE_MAX) ? UART_BLOCK_SIZE_MAX : remaining;
        HAL_UART_Transmit(&huart1, ptr, chunk, HAL_MAX_DELAY);
        ptr += chunk;
        remaining -= chunk;
        HAL_Delay(1);
    }
    return EMBEDDIP_OK;
}

// Define the object
serial_t stm32_uart = {
    .init = serial_init,
    .capture = serial_capture,
    .send = serial_send,
    .sendJPEG = serial_send_jpeg,
    .send1D = serial_send_1d,
    .flush = serial_flush,
};

#endif
