# Board profile: STM32N6570-DK

if(NOT IS_DIRECTORY "${EMBEDDIP_STM32CUBE_N6_ROOT}")
    message(FATAL_ERROR
        "EMBEDDIP_STM32CUBE_N6_ROOT must name an existing STM32CubeN6 SDK directory: "
        "'${EMBEDDIP_STM32CUBE_N6_ROOT}'")
endif()

set(EMBEDDIP_BOARD_SOURCES
    ${BOARD_COMMON_SOURCES}
    board/stm32n6/board_stm32n6_memory.c
)

set(EMBEDDIP_DEVICE_SOURCES)

set(EMBEDDIP_BOARD_DEFINES
    EMBED_DIP_BOARD_STM32N6=1
    STM32N6xx
    STM32N657xx
)

set(EMBEDDIP_BOARD_INCLUDE_DIRS
    ${CMAKE_CURRENT_SOURCE_DIR}/board/stm32n6
    ${EMBEDDIP_STM32CUBE_N6_ROOT}/Drivers/CMSIS/Device/ST/STM32N6xx/Include
    ${EMBEDDIP_STM32CUBE_N6_ROOT}/Drivers/CMSIS/Core/Include
    ${EMBEDDIP_STM32CUBE_N6_ROOT}/Drivers/CMSIS/DSP/Include
)
