/**
 * @file board_init.c
 * @brief STM32F746G-Discovery board initialization
 *
 * This file contains board-specific initialization code:
 * - GPIO configuration for camera, LCD, UART
 * - Peripheral initialization
 * - Calls architecture layer for CPU setup
 *
 * @note This file contains ONLY board-specific code
 * @note CPU/architecture initialization is in arch/ layer
 */

#include "board_config.h"
#include "arch/arch.h"

#ifdef BOARD_STM32F746G_DISCOVERY

#include "stm32f7xx_hal.h"
#include <stdio.h>

// External peripheral handles (typically generated by STM32CubeMX)
extern UART_HandleTypeDef huart1;
extern LTDC_HandleTypeDef hltdc;
extern DMA2D_HandleTypeDef hdma2d;
extern DCMI_HandleTypeDef hdcmi;

// ============================================================================
// Forward Declarations
// ============================================================================
static void board_gpio_init(void);
static void board_camera_pins_init(void);
static void board_lcd_pins_init(void);
static void board_uart_pins_init(void);

// ============================================================================
// Main Board Initialization
// ============================================================================

/**
 * @brief Initialize the STM32F746G-Discovery board
 *
 * Call this function once during startup. It will:
 * 1. Initialize architecture layer (CPU, FPU, cache)
 * 2. Configure board-specific GPIOs
 * 3. Initialize peripherals
 */
void board_init(void) {
    // Initialize STM32 HAL library
    HAL_Init();

    // Configure system clock (216 MHz from external crystal)
    SystemClock_Config();

    // Initialize architecture layer (CPU, FPU, cache, memory)
    arch_init();
    arch_memory_init();

    // Initialize board-specific GPIOs
    board_gpio_init();

    // Initialize peripherals
    board_camera_pins_init();
    board_lcd_pins_init();
    board_uart_pins_init();

    // Print board info to UART
    printf("\r\n");
    printf("========================================\r\n");
    printf("Board: %s\r\n", BOARD_NAME);
    printf("MCU: %s\r\n", BOARD_MCU);
    printf("CPU Frequency: %lu MHz\r\n", BOARD_CPU_CLOCK_HZ / 1000000);
    printf("Architecture: %s\r\n", arch_get_name());
    printf("========================================\r\n");
    printf("Memory Configuration:\r\n");
    printf("  Internal SRAM: %d KB\r\n", BOARD_SRAM_SIZE / 1024);
    printf("  External SDRAM: %d MB\r\n", BOARD_SDRAM_SIZE / (1024 * 1024));
    printf("  Framebuffer: %d KB @ 0x%08lX\r\n",
           BOARD_FRAMEBUFFER_SIZE_ALIGNED / 1024,
           (unsigned long)BOARD_FRAMEBUFFER_BASE);
    printf("  Memory Pool: %d MB @ 0x%08lX\r\n",
           BOARD_MEMORY_POOL_SIZE / (1024 * 1024),
           (unsigned long)BOARD_MEMORY_POOL_BASE);
    printf("========================================\r\n");
}

// ============================================================================
// GPIO Initialization
// ============================================================================

static void board_gpio_init(void) {
    // Enable all GPIO clocks
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();
    __HAL_RCC_GPIOE_CLK_ENABLE();
    __HAL_RCC_GPIOF_CLK_ENABLE();
    __HAL_RCC_GPIOG_CLK_ENABLE();
    __HAL_RCC_GPIOH_CLK_ENABLE();
    __HAL_RCC_GPIOI_CLK_ENABLE();
    __HAL_RCC_GPIOJ_CLK_ENABLE();
    __HAL_RCC_GPIOK_CLK_ENABLE();
}

// ============================================================================
// Camera Pin Initialization
// ============================================================================

static void board_camera_pins_init(void) {
    GPIO_InitTypeDef gpio_init = {0};

    // Camera power control pin (PH13)
    gpio_init.Pin = BOARD_CAMERA_PWR_PIN;
    gpio_init.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init.Pull = GPIO_NOPULL;
    gpio_init.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(BOARD_CAMERA_PWR_PORT, &gpio_init);

    // Camera reset pin (PH14)
    gpio_init.Pin = BOARD_CAMERA_RST_PIN;
    HAL_GPIO_Init(BOARD_CAMERA_RST_PORT, &gpio_init);

    // Power off camera initially
    HAL_GPIO_WritePin(BOARD_CAMERA_PWR_PORT, BOARD_CAMERA_PWR_PIN, GPIO_PIN_RESET);

    // Hold camera in reset
    HAL_GPIO_WritePin(BOARD_CAMERA_RST_PORT, BOARD_CAMERA_RST_PIN, GPIO_PIN_RESET);

    printf("[Board] Camera pins initialized\r\n");
}

/**
 * @brief Power on the camera module
 */
void board_camera_power_on(void) {
    // Release reset
    HAL_GPIO_WritePin(BOARD_CAMERA_RST_PORT, BOARD_CAMERA_RST_PIN, GPIO_PIN_SET);
    HAL_Delay(10);

    // Power on (active high)
    HAL_GPIO_WritePin(BOARD_CAMERA_PWR_PORT, BOARD_CAMERA_PWR_PIN, GPIO_PIN_SET);
    HAL_Delay(50);

    printf("[Board] Camera powered on\r\n");
}

/**
 * @brief Power off the camera module
 */
void board_camera_power_off(void) {
    // Power off
    HAL_GPIO_WritePin(BOARD_CAMERA_PWR_PORT, BOARD_CAMERA_PWR_PIN, GPIO_PIN_RESET);

    // Assert reset
    HAL_GPIO_WritePin(BOARD_CAMERA_RST_PORT, BOARD_CAMERA_RST_PIN, GPIO_PIN_RESET);

    printf("[Board] Camera powered off\r\n");
}

// ============================================================================
// LCD Pin Initialization
// ============================================================================

static void board_lcd_pins_init(void) {
    GPIO_InitTypeDef gpio_init = {0};

    // LCD backlight control (PK3)
    __HAL_RCC_GPIOK_CLK_ENABLE();

    gpio_init.Pin = BOARD_LCD_BL_CTRL_PIN;
    gpio_init.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init.Pull = GPIO_NOPULL;
    gpio_init.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(BOARD_LCD_BL_CTRL_PORT, &gpio_init);

    // Turn off backlight initially
    HAL_GPIO_WritePin(BOARD_LCD_BL_CTRL_PORT, BOARD_LCD_BL_CTRL_PIN, GPIO_PIN_RESET);

    printf("[Board] LCD pins initialized\r\n");
}

/**
 * @brief Turn on LCD backlight
 */
void board_lcd_backlight_on(void) {
    HAL_GPIO_WritePin(BOARD_LCD_BL_CTRL_PORT, BOARD_LCD_BL_CTRL_PIN, GPIO_PIN_SET);
}

/**
 * @brief Turn off LCD backlight
 */
void board_lcd_backlight_off(void) {
    HAL_GPIO_WritePin(BOARD_LCD_BL_CTRL_PORT, BOARD_LCD_BL_CTRL_PIN, GPIO_PIN_RESET);
}

// ============================================================================
// UART Pin Initialization
// ============================================================================

static void board_uart_pins_init(void) {
    GPIO_InitTypeDef gpio_init = {0};

    // Enable USART1 clock
    __HAL_RCC_USART1_CLK_ENABLE();

    // Configure USART1 pins (PA9: TX, PA10: RX)
    gpio_init.Pin = BOARD_UART_TX_PIN | BOARD_UART_RX_PIN;
    gpio_init.Mode = GPIO_MODE_AF_PP;
    gpio_init.Pull = GPIO_NOPULL;
    gpio_init.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    gpio_init.Alternate = GPIO_AF7_USART1;
    HAL_GPIO_Init(GPIOA, &gpio_init);

    // Configure UART parameters
    huart1.Instance = USART1;
    huart1.Init.BaudRate = BOARD_UART_DEFAULT_BAUDRATE;
    huart1.Init.WordLength = UART_WORDLENGTH_8B;
    huart1.Init.StopBits = UART_STOPBITS_1;
    huart1.Init.Parity = UART_PARITY_NONE;
    huart1.Init.Mode = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;

    if (HAL_UART_Init(&huart1) != HAL_OK) {
        // Initialization error
        while(1);
    }

    printf("[Board] UART1 initialized at %lu baud\r\n", BOARD_UART_DEFAULT_BAUDRATE);
}

// ============================================================================
// Retarget printf to UART (for debugging)
// ============================================================================

#ifdef __GNUC__
int _write(int file, char *ptr, int len) {
    HAL_UART_Transmit(&huart1, (uint8_t*)ptr, len, HAL_MAX_DELAY);
    return len;
}
#endif

#endif // BOARD_STM32F746G_DISCOVERY
