#include "serial.h"
#include "stm32f7xx_hal.h"
#include <stdio.h>
#include <stdarg.h>
#include "stm32746g_discovery.h"
#include "stm32746g_discovery_sdram.h"
#include "rk043fn48h.h"
#include "fonts.h"
#include "display.h"
#include "configs.h"

// Use the UART handle generated by STM32CubeMX
extern DCMI_HandleTypeDef hdcmi;
extern LTDC_HandleTypeDef hltdc;

static void display_init(void)
{
    __HAL_DCMI_DISABLE_IT(&hdcmi, DCMI_IT_LINE | DCMI_IT_VSYNC);
    HAL_LTDC_SetAddress(&hltdc, FRAME_BUFFER + 0x100000,
                        LTDC_LAYER_1);
    HAL_LTDC_Reload(&hltdc, LTDC_RELOAD_IMMEDIATE);
}

static void display_deinit(void)
{
    HAL_LTDC_DeInit(&hdcmi);
}

static void display_reset(void)
{
    // No config
}

#define LCD_FRAMEBUFFER ((uint16_t *)FRAME_BUFFER + 0x100000)
#define LCD_WIDTH 480
#define LCD_HEIGHT 272

static void display_clear(display_rgb565_color_t color)
{
    for (uint32_t i = 0; i < (LCD_WIDTH * LCD_HEIGHT); i++)
    {
        LCD_FRAMEBUFFER[i] = color;
    }

    // Reset to the default array.
    HAL_LTDC_SetAddress(&hltdc, LCD_FRAMEBUFFER,
                        LTDC_LAYER_1);
}

static void display_show(Image *inImg)
{

    switch (inImg->format)
    {
    case IMAGE_FORMAT_RGB565:
    {
        HAL_LTDC_SetPixelFormat(&hltdc, LTDC_PIXEL_FORMAT_RGB565, LTDC_LAYER_1);
        break;
    }
    case IMAGE_FORMAT_GRAYSCALE:
    {
        HAL_LTDC_SetPixelFormat(&hltdc, LTDC_PIXEL_FORMAT_L8, LTDC_LAYER_1);
        break;
    }
    default:
    {
        // should not go there
        return;
    }
    }

    HAL_LTDC_SetAddress(&hltdc, inImg->pixels_u8,
                        LTDC_LAYER_1);
    HAL_LTDC_Reload(&hltdc, LTDC_RELOAD_IMMEDIATE);
}

display_t stm32_rk043fn48h = {
    .init = display_init,
    .show = display_show,
    .clear = display_clear,
};