#include "serial.h"
#include "stm32f7xx_hal.h"
#include <stdio.h>
#include <stdarg.h>
#include "stm32746g_discovery.h"
#include "stm32746g_discovery_sdram.h"
#include "rk043fn48h.h"
#include "fonts.h"
#include "display.h"
#include "configs.h"

// Use the UART handle generated by STM32CubeMX
extern UART_HandleTypeDef huart1;
extern DCMI_HandleTypeDef hdcmi;
extern DMA_HandleTypeDef hdma_dcmi;
extern DMA2D_HandleTypeDef hdma2d;
extern LTDC_HandleTypeDef hltdc;

static volatile uint32_t start_the_camera_capture = 0;
typedef enum
{
    CAMERA_OK = 0x00,
    CAMERA_ERROR = 0x01,
    CAMERA_TIMEOUT = 0x02,
    CAMERA_NOT_DETECTED = 0x03,
    CAMERA_NOT_SUPPORTED = 0x04
} Camera_StatusTypeDef;

typedef struct
{
    uint32_t TextColor;
    uint32_t BackColor;
    sFONT *pFont;
} LCD_DrawPropTypeDef;

typedef struct
{
    int16_t X;
    int16_t Y;
} Point, *pPoint;

static LCD_DrawPropTypeDef DrawProp[2];

LTDC_LayerCfgTypeDef layer_cfg;
static RCC_PeriphCLKInitTypeDef periph_clk_init_struct;

/* Camera resolution is QWVGA (480x272) */
static uint32_t CameraResX = QVGA_RES_X;
static uint32_t CameraResY = QVGA_RES_Y;
static uint32_t LcdResX = WQVGA_RES_X; /* QWVGA landscape */
static uint32_t LcdResY = WQVGA_RES_Y;

void LCD_GPIO_Init(LTDC_HandleTypeDef *hltdc, void *Params)
{
    GPIO_InitTypeDef gpio_init_structure;
    /* Enable the LTDC and DMA2D clocks */
    __HAL_RCC_LTDC_CLK_ENABLE();
    __HAL_RCC_DMA2D_CLK_ENABLE();
    /* Enable GPIOs clock */
    __HAL_RCC_GPIOE_CLK_ENABLE();
    __HAL_RCC_GPIOG_CLK_ENABLE();
    __HAL_RCC_GPIOI_CLK_ENABLE();
    __HAL_RCC_GPIOJ_CLK_ENABLE();
    __HAL_RCC_GPIOK_CLK_ENABLE();
    /*** LTDC Pins configuration ***/
    /* GPIOE configuration */
    gpio_init_structure.Pin = GPIO_PIN_4;
    gpio_init_structure.Mode = GPIO_MODE_AF_PP;
    gpio_init_structure.Pull = GPIO_NOPULL;
    gpio_init_structure.Speed = GPIO_SPEED_FAST;
    gpio_init_structure.Alternate = GPIO_AF14_LTDC;
    HAL_GPIO_Init(GPIOE, &gpio_init_structure);
    /* GPIOG configuration */
    gpio_init_structure.Pin = GPIO_PIN_12;
    gpio_init_structure.Mode = GPIO_MODE_AF_PP;
    gpio_init_structure.Alternate = GPIO_AF9_LTDC;
    HAL_GPIO_Init(GPIOG, &gpio_init_structure);
    /* GPIOI LTDC alternate configuration */
    gpio_init_structure.Pin = GPIO_PIN_9 | GPIO_PIN_10 | GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15;
    gpio_init_structure.Mode = GPIO_MODE_AF_PP;
    gpio_init_structure.Alternate = GPIO_AF14_LTDC;
    HAL_GPIO_Init(GPIOI, &gpio_init_structure);
    /* GPIOJ configuration */
    gpio_init_structure.Pin = GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 |
                              GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7 | GPIO_PIN_8 | GPIO_PIN_9 | GPIO_PIN_10 | GPIO_PIN_11 | GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15;
    gpio_init_structure.Mode = GPIO_MODE_AF_PP;
    gpio_init_structure.Alternate = GPIO_AF14_LTDC;
    HAL_GPIO_Init(GPIOJ, &gpio_init_structure);
    /* GPIOK configuration */
    gpio_init_structure.Pin = GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7;
    gpio_init_structure.Mode = GPIO_MODE_AF_PP;
    gpio_init_structure.Alternate = GPIO_AF14_LTDC;
    HAL_GPIO_Init(GPIOK, &gpio_init_structure);
    /* LCD_DISP GPIO configuration */
    gpio_init_structure.Pin = GPIO_PIN_12; /* LCD_DISP pin has to be manually controlled */
    gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
    HAL_GPIO_Init(GPIOI, &gpio_init_structure);
    /* LCD_BL_CTRL GPIO configuration */
    gpio_init_structure.Pin = GPIO_PIN_3; /* LCD_BL_CTRL pin has to be manually controlled */
    gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
    HAL_GPIO_Init(GPIOK, &gpio_init_structure);
}

static void LTDC_Init(uint32_t FB_Address, uint16_t Xpos, uint16_t Ypos, uint16_t Width, uint16_t Height)
{
    /* Timing Configuration */
    hltdc.Init.HorizontalSync = (RK043FN48H_HSYNC - 1);
    hltdc.Init.VerticalSync = (RK043FN48H_VSYNC - 1);
    hltdc.Init.AccumulatedHBP = (RK043FN48H_HSYNC + RK043FN48H_HBP - 1);
    hltdc.Init.AccumulatedVBP = (RK043FN48H_VSYNC + RK043FN48H_VBP - 1);
    hltdc.Init.AccumulatedActiveH = (RK043FN48H_HEIGHT + RK043FN48H_VSYNC + RK043FN48H_VBP - 1);
    hltdc.Init.AccumulatedActiveW = (RK043FN48H_WIDTH + RK043FN48H_HSYNC + RK043FN48H_HBP - 1);
    hltdc.Init.TotalHeigh = (RK043FN48H_HEIGHT + RK043FN48H_VSYNC + RK043FN48H_VBP + RK043FN48H_VFP - 1);
    hltdc.Init.TotalWidth = (RK043FN48H_WIDTH + RK043FN48H_HSYNC + RK043FN48H_HBP + RK043FN48H_HFP - 1);

    /* LCD clock configuration */
    periph_clk_init_struct.PeriphClockSelection = RCC_PERIPHCLK_LTDC;
    periph_clk_init_struct.PLLSAI.PLLSAIN = 192;
    periph_clk_init_struct.PLLSAI.PLLSAIR = RK043FN48H_FREQUENCY_DIVIDER;
    periph_clk_init_struct.PLLSAIDivR = RCC_PLLSAIDIVR_4;
    HAL_RCCEx_PeriphCLKConfig(&periph_clk_init_struct);

    /* Initialize the LCD pixel width and pixel height */
    hltdc.LayerCfg->ImageWidth = RK043FN48H_WIDTH;
    hltdc.LayerCfg->ImageHeight = RK043FN48H_HEIGHT;
    hltdc.Init.Backcolor.Blue = 0;

    /* Background value */
    hltdc.Init.Backcolor.Green = 0;
    hltdc.Init.Backcolor.Red = 0;

    /* Polarity */
    hltdc.Init.HSPolarity = LTDC_HSPOLARITY_AL;
    hltdc.Init.VSPolarity = LTDC_VSPOLARITY_AL;
    hltdc.Init.DEPolarity = LTDC_DEPOLARITY_AL;
    hltdc.Init.PCPolarity = LTDC_PCPOLARITY_IPC;
    hltdc.Instance = LTDC;
    if (HAL_LTDC_GetState(&hltdc) == HAL_LTDC_STATE_RESET)
    {
        LCD_GPIO_Init(&hltdc, NULL);
    }
    HAL_LTDC_Init(&hltdc);

    /* Assert display enable LCD_DISP pin */
    HAL_GPIO_WritePin(GPIOI, GPIO_PIN_12, GPIO_PIN_SET);
    /* Assert backlight LCD_BL_CTRL pin */
    HAL_GPIO_WritePin(GPIOK, GPIO_PIN_3, GPIO_PIN_SET);
    DrawProp[0].pFont = &Font24;
    /* Layer Init */
    layer_cfg.WindowX0 = Xpos;
    layer_cfg.WindowX1 = Width;
    layer_cfg.WindowY0 = Ypos;
    layer_cfg.WindowY1 = Height;
    layer_cfg.PixelFormat = LTDC_PIXEL_FORMAT_RGB565;
    layer_cfg.FBStartAdress = FB_Address;
    layer_cfg.Alpha = 255;
    layer_cfg.Alpha0 = 0;
    layer_cfg.Backcolor.Blue = 0;
    layer_cfg.Backcolor.Green = 0;
    layer_cfg.Backcolor.Red = 0;
    layer_cfg.BlendingFactor1 = LTDC_BLENDING_FACTOR1_PAxCA;
    layer_cfg.BlendingFactor2 = LTDC_BLENDING_FACTOR2_PAxCA;
    layer_cfg.ImageWidth = Width;
    layer_cfg.ImageHeight = Height;
    HAL_LTDC_ConfigLayer(&hltdc, &layer_cfg, 1);

    DrawProp[1].BackColor = ((uint32_t)0xFFFFFFFF);
    DrawProp[1].pFont = &Font24;
    DrawProp[1].TextColor = ((uint32_t)0xFF000000);
}

/**
 * @brief  Converts a line to an ARGB8888 pixel format.
 * @param  pSrc: Pointer to source buffer
 * @param  pDst: Output color
 * @param  ColorMode: Input color mode
 * @retval None
 */
static void LCD_LL_ConvertLineToARGB8888(void *pSrc, void *pDst)
{
    /* Enable DMA2D clock */
    __HAL_RCC_DMA2D_CLK_ENABLE();

    /* Configure the DMA2D Mode, Color Mode and output offset */
    hdma2d.Init.Mode = DMA2D_M2M_PFC;
    hdma2d.Init.ColorMode = DMA2D_OUTPUT_RGB565; // DMA2D_OUTPUT_ARGB8888; /* Output color out of PFC */
    hdma2d.Init.OutputOffset = 0;
    // hdma2d.Init.AlphaInverted = DMA2D_REGULAR_ALPHA;  /* No Output Alpha Inversion*/
    // hdma2d.Init.RedBlueSwap   = DMA2D_RB_REGULAR;     /* No Output Red & Blue swap */

    // DMA2D_INPUT_ARGB8888        0x00000000U  /*!< ARGB8888 color mode */
    // DMA2D_INPUT_RGB888          0x00000001U  /*!< RGB888 color mode   */
    // DMA2D_INPUT_RGB565          0x00000002U  /*!< RGB565 color mode   */
    // DMA2D_INPUT_ARGB1555        0x00000003U  /*!< ARGB1555 color mode */
    // DMA2D_INPUT_ARGB4444        0x00000004U  /*!< ARGB4444 color mode */
    // DMA2D_INPUT_L8              0x00000005U  /*!< L8 color mode       */
    // DMA2D_INPUT_AL44            0x00000006U  /*!< AL44 color mode     */
    // DMA2D_INPUT_AL88            0x00000007U  /*!< AL88 color mode     */
    // DMA2D_INPUT_L4              0x00000008U  /*!< L4 color mode       */
    // DMA2D_INPUT_A8              0x00000009U  /*!< A8 color mode       */
    // DMA2D_INPUT_A4              0x0000000AU  /*!< A4 color mode       */

    /* Foreground Configuration */
    hdma2d.LayerCfg[1].AlphaMode = DMA2D_NO_MODIF_ALPHA;
    hdma2d.LayerCfg[1].InputAlpha = 0xFF; /* fully opaque */
    hdma2d.LayerCfg[1].InputColorMode = DMA2D_INPUT_RGB565;
    hdma2d.LayerCfg[1].InputOffset = 0;
    // hdma2d.LayerCfg[1].RedBlueSwap = DMA2D_RB_REGULAR; /* No ForeGround Red/Blue swap */
    // hdma2d.LayerCfg[1].AlphaInverted = DMA2D_REGULAR_ALPHA; /* No ForeGround Alpha inversion */

    hdma2d.Instance = DMA2D;

    /* DMA2D Initialization */
    if (HAL_DMA2D_Init(&hdma2d) == HAL_OK)
    {
        if (HAL_DMA2D_ConfigLayer(&hdma2d, 1) == HAL_OK)
        {
            if (HAL_DMA2D_Start(&hdma2d, (uint32_t)pSrc, (uint32_t)pDst, CameraResX, 1) == HAL_OK)
            {
                /* Polling For DMA transfer */
                HAL_DMA2D_PollForTransfer(&hdma2d, 10);
            }
        }
    }
    else
    {
        while (1)
            ;
    }
}

/**
 * @brief  Camera Frame Event callback.
 */
void HAL_DCMI_FrameEventCallback(DCMI_HandleTypeDef *hdcmi)
{
    start_the_camera_capture = 1;
}

/**
 * @brief  Camera line event callback
 * @param  None
 * @retval None
 */
// void HAL_DCMI_FrameEventCallback(DCMI_HandleTypeDef *hdcmi)
//{
//	if (offset_lcd == 0) // ASSUMPTION Camera resolution is lower than LCD resolution
//	{
//		/* If Camera resolution is lower than LCD resolution, set display in the middle of the screen */
//		offset_lcd =   ((((LcdResY - CameraResY) / 2) * LcdResX)   /* Middle of the screen on Y axis */
//				+   ((LcdResX - CameraResX) / 2))             /* Middle of the screen on X axis */
//     				  * sizeof(uint32_t);
//	}
//
//	for(uint32_t camera_line_nb = 0; camera_line_nb < CameraResY; camera_line_nb++)
//	{
////		LCD_LL_ConvertLineToARGB8888((uint32_t *)(CAMERA_FRAME_BUFFER + offset_cam),
////				(uint32_t *)(LCD_FRAME_BUFFER + offset_lcd));
//
//		for (uint32_t ncol=0; ncol<CameraResX; ncol ++){
//			uint32_t val = (CAMERA_FRAME_BUFFER + offset_cam+4*ncol);
//			*(__IO uint32_t*)(4*ncol+LCD_FRAME_BUFFER) = val;
//		}
//
//		offset_cam  = offset_cam + (CameraResX * sizeof(uint16_t));
//		offset_lcd  = offset_lcd + (LcdResX * sizeof(uint32_t));
//	}
//}

static void test_ConvertLineRGB565ToARGB8888()
{
    // white/magenta test color pattern
    uint32_t offset_cam = 0;
    uint32_t offset_lcd = 0;

    for (uint32_t pos = 0; pos < LcdResX * LcdResY / 2; pos++)
    {
        uint32_t val = LCD_RGB565_COLOR_WHITE << 16 | LCD_RGB565_COLOR_DARKMAGENTA;
        *(__IO uint32_t *)(4 * pos + CAMERA_FRAME_BUFFER) = val;
    }

    for (uint32_t camera_line_nb = 0; camera_line_nb < CameraResY; camera_line_nb++)
    {
        LCD_LL_ConvertLineToARGB8888((uint32_t *)(CAMERA_FRAME_BUFFER + offset_cam),
                                     (uint32_t *)(LCD_FRAME_BUFFER + offset_lcd));

        offset_cam = offset_cam + (CameraResX * sizeof(uint16_t));
        offset_lcd = offset_lcd + (LcdResX * sizeof(uint32_t));
    }
}

static void display_init(void)
{
    __HAL_DCMI_DISABLE_IT(&hdcmi, DCMI_IT_LINE | DCMI_IT_VSYNC);
    LTDC_Init(FRAME_BUFFER + 0x100000, 0, 0, 480, 272);
}

static void display_show(Image *inImg)
{
    LTDC_Init(inImg->pixels_u8, 0, 0, 480, 272);
}

display_t stm32_rk043fn48h = {
    .init = display_init,
    .show = display_show};