// SPDX-License-Identifier: MIT
// Copyright (c) 2025 EmbedDIP

#include <embedDIP_configs.h>

#ifdef DEVICE_RK043FN48H

    #include "board/stm32f7/configs.h"
    #include "core/error.h"
    #include "device/display/display.h"
    #include "device/serial/serial.h"

    #include <stdarg.h>
    #include <stdio.h>

    #include "stm32f7xx_hal.h"

// Use the UART handle generated by STM32CubeMX
extern DCMI_HandleTypeDef hdcmi;
extern LTDC_HandleTypeDef hltdc;

static int display_init(void)
{
    HAL_LTDC_SetAddress(&hltdc, FRAME_BUFFER + 0x100000, LTDC_LAYER_1);
    HAL_LTDC_Reload(&hltdc, LTDC_RELOAD_IMMEDIATE);
    return EMBEDDIP_OK;
}

static int display_deinit(void)
{
    HAL_LTDC_DeInit(&hltdc);
    return EMBEDDIP_OK;
}

static int display_reset(void)
{
    // No config
    return EMBEDDIP_OK;
}

    #define LCD_FRAMEBUFFER ((uint32_t *)(FRAME_BUFFER + 0x100000))
    #define LCD_WIDTH 480
    #define LCD_HEIGHT 272

static int display_clear(displayColor color)
{
    for (uint32_t i = 0; i < (LCD_WIDTH * LCD_HEIGHT); i++) {
        LCD_FRAMEBUFFER[i] = color;
    }

    // Reset to the default array.
    HAL_LTDC_SetAddress(&hltdc, (uint32_t)LCD_FRAMEBUFFER, LTDC_LAYER_1);
    return EMBEDDIP_OK;
}

static int display_show(Image *inImg)
{
    if (!inImg) {
        return EMBEDDIP_ERROR_NULL_PTR;
    }

    switch (inImg->format) {
    case IMAGE_FORMAT_RGB888: {
        HAL_LTDC_SetPixelFormat(&hltdc, LTDC_PIXEL_FORMAT_RGB888, LTDC_LAYER_1);
        break;
    }
    case IMAGE_FORMAT_RGB565: {
        HAL_LTDC_SetPixelFormat(&hltdc, LTDC_PIXEL_FORMAT_RGB565, LTDC_LAYER_1);
        break;
    }
    case IMAGE_FORMAT_GRAYSCALE: {
        HAL_LTDC_SetPixelFormat(&hltdc, LTDC_PIXEL_FORMAT_L8, LTDC_LAYER_1);
        break;
    }
    default: {
        return EMBEDDIP_ERROR_INVALID_FORMAT;
    }
    }

    HAL_LTDC_SetWindowSize(&hltdc, inImg->width, inImg->height, LTDC_LAYER_1);
    HAL_LTDC_SetAddress(&hltdc, (uint32_t)inImg->pixels, LTDC_LAYER_1);
    HAL_LTDC_Reload(&hltdc, LTDC_RELOAD_IMMEDIATE);
    return EMBEDDIP_OK;
}

display_t stm32_ota5180a = {
    .init = display_init,
    .deinit = display_deinit,
    .reset = display_reset,
    .clear = display_clear,
    .show = display_show,
};

#endif