#include "device/serial/serial.h"
#include "stm32f7xx_hal.h"
#include <stdio.h>
#include <stdarg.h>
#include "stm32746g_discovery.h"
#include "stm32746g_discovery_sdram.h"
#include "ov5640.h"
#include "device/display/rk043fn48h/rk043fn48h.h"
#include "device/display/rk043fn48h/fonts.h"
#include "device/camera/camera.h"
#include "board/stm32f7/configs.h"

// Use the UART handle generated by STM32CubeMX
extern DCMI_HandleTypeDef hdcmi;
extern DMA2D_HandleTypeDef hdma2d;

static volatile uint32_t start_the_camera_capture = 0;
typedef enum
{
    CAMERA_OK = 0x00,
    CAMERA_ERROR = 0x01,
    CAMERA_TIMEOUT = 0x02,
    CAMERA_NOT_DETECTED = 0x03,
    CAMERA_NOT_SUPPORTED = 0x04
} Camera_StatusTypeDef;

CAMERA_DrvTypeDef *camera_driv;
/* Camera module I2C HW address */
static uint32_t CameraHwAddress;
/* Image size */
uint32_t Im_size = 0;

/* Camera resolution is QWVGA (480x272) */
static uint32_t CameraResX = QVGA_RES_X;
static uint32_t CameraResY = QVGA_RES_Y;
static uint32_t LcdResX = WQVGA_RES_X; /* QWVGA landscape */
static uint32_t LcdResY = WQVGA_RES_Y;

static uint32_t offset_cam = 0;
static uint32_t offset_lcd = 0;

__IO uint16_t pBuffer[QVGA_RES_X * QVGA_RES_Y];
HAL_StatusTypeDef hal_status = HAL_OK;

uint8_t CAMERA_Init(uint32_t Resolution) /*Camera initialization*/
{
}

/**
 * @brief  CANERA power up
 * @retval None
 */
void CAMERA_PwrUp(void)
{
    GPIO_InitTypeDef gpio_init_structure;

    /* Enable GPIO clock */
    __HAL_RCC_GPIOH_CLK_ENABLE();

    /*** Configure the GPIO ***/
    /* Configure DCMI GPIO as alternate function */
    gpio_init_structure.Pin = GPIO_PIN_13;
    gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init_structure.Pull = GPIO_NOPULL;
    gpio_init_structure.Speed = GPIO_SPEED_HIGH;
    HAL_GPIO_Init(GPIOH, &gpio_init_structure);

    /* De-assert the camera POWER_DOWN pin (active high) */
    HAL_GPIO_WritePin(GPIOH, GPIO_PIN_13, GPIO_PIN_RESET);

    HAL_Delay(3); /* POWER_DOWN de-asserted during 3ms */
}

/**
 * @brief  CAMERA power down
 * @retval None
 */
void CAMERA_PwrDown(void)
{
    GPIO_InitTypeDef gpio_init_structure;

    /* Enable GPIO clock */
    __HAL_RCC_GPIOH_CLK_ENABLE();

    /*** Configure the GPIO ***/
    /* Configure DCMI GPIO as alternate function */
    gpio_init_structure.Pin = GPIO_PIN_13;
    gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init_structure.Pull = GPIO_NOPULL;
    gpio_init_structure.Speed = GPIO_SPEED_HIGH;
    HAL_GPIO_Init(GPIOH, &gpio_init_structure);

    /* Assert the camera POWER_DOWN pin (active high) */
    HAL_GPIO_WritePin(GPIOH, GPIO_PIN_13, GPIO_PIN_SET);
}

static void test_ConvertLineRGB565ToARGB8888()
{
    // white/magenta test color pattern
    uint32_t offset_cam = 0;
    uint32_t offset_lcd = 0;

    for (uint32_t pos = 0; pos < LcdResX * LcdResY / 2; pos++)
    {
        uint32_t val = LCD_RGB565_COLOR_WHITE << 16 | LCD_RGB565_COLOR_DARKMAGENTA;
        *(__IO uint32_t *)(4 * pos + CAMERA_FRAME_BUFFER) = val;
    }

    for (uint32_t camera_line_nb = 0; camera_line_nb < CameraResY; camera_line_nb++)
    {
        LCD_LL_ConvertLineToARGB8888((uint32_t *)(CAMERA_FRAME_BUFFER + offset_cam),
                                     (uint32_t *)(LCD_FRAME_BUFFER + offset_lcd));

        offset_cam = offset_cam + (CameraResX * sizeof(uint16_t));
        offset_lcd = offset_lcd + (LcdResX * sizeof(uint32_t));
    }
}

static void camera_init(ImageResolution resolution)
{

#define IMAGE_RES_QQVGA 0
#define IMAGE_RES_QVGA 1
#define IMAGE_RES_WQVGA 2
#define IMAGE_RES_VGA 3

    CAMERA_PwrDown();
    // hal_status = BSP_SDRAM_Init();

    CAMERA_PwrUp();
    HAL_Delay(1000);

    uint8_t status = CAMERA_ERROR;
    /* Read ID of Camera module via I2C */
    if (ov5640_ReadID(CAMERA_I2C_ADDRESS) == OV5640_ID)
    {
        camera_driv = &ov5640_drv;
        /* Initialize the camera driver structure */
        camera_driv->Init(CAMERA_I2C_ADDRESS, resolution);
        HAL_DCMI_DisableCROP(&hdcmi);
        HAL_Delay(500);

        status = CAMERA_OK; /* Return CAMERA_OK status */
    }
    else
    {
        status = CAMERA_NOT_SUPPORTED; /* Return CAMERA_NOT_SUPPORTED status */
    }

    HAL_Delay(1000); // Delay for the camera to output correct data
    __HAL_DCMI_DISABLE_IT(&hdcmi, DCMI_IT_LINE | DCMI_IT_VSYNC);
}

static void camera_capture(captureMode mode, Image *inImg)
{

    CAMERA_PwrDown();
    CAMERA_PwrUp();

    switch (inImg->format)
    {
    case IMAGE_FORMAT_GRAYSCALE:
        break;
    case IMAGE_FORMAT_RGB565:
        break;
    default:
        break;
    }

    // TODO

    HAL_DCMI_Start_DMA(&hdcmi, mode == CONTINUOUS ? DCMI_MODE_CONTINUOUS : DCMI_MODE_SNAPSHOT, (uint32_t)inImg->pixels, inImg->size / 2);
}

static void camera_stop(void)
{
    HAL_DCMI_Stop(&hdcmi);
}

static void camera_setRes(ImageResolution resolution)
{

    CAMERA_PwrDown();
    CAMERA_PwrUp();

    uint8_t status = CAMERA_ERROR;
    /* Read ID of Camera module via I2C */
    if (ov5640_ReadID(CAMERA_I2C_ADDRESS) == OV5640_ID)
    {
        camera_driv = &ov5640_drv;
        /* Initialize the camera driver structure */
        camera_driv->Init(CAMERA_I2C_ADDRESS, resolution);
        HAL_DCMI_DisableCROP(&hdcmi);
        HAL_Delay(500);

        status = CAMERA_OK; /* Return CAMERA_OK status */
    }
    else
    {
        status = CAMERA_NOT_SUPPORTED; /* Return CAMERA_NOT_SUPPORTED status */
    }

    HAL_Delay(1000); // Delay for the camera to output correct data
    __HAL_DCMI_DISABLE_IT(&hdcmi, DCMI_IT_LINE | DCMI_IT_VSYNC);
}

camera_t stm32_ov5640 = {
    .init = camera_init,
    .capture = camera_capture,
    .stop = camera_stop,
    .setRes = camera_setRes};