#include <embedDIP_configs.h>

#ifdef DEVICE_OV5640

#include "device/serial/serial.h"
#include "stm32f7xx_hal.h"
#include <stdio.h>
#include <stdarg.h>
#include "stm32746g_discovery.h"
#include "ov5640.h"
#include "device/display/rk043fn48h/rk043fn48h.h"
#include "device/display/rk043fn48h/fonts.h"
#include "device/camera/camera.h"
#include "board/stm32f7/configs.h"

// Use the UART handle generated by STM32CubeMX
extern DCMI_HandleTypeDef hdcmi;
extern DMA2D_HandleTypeDef hdma2d;

static volatile uint32_t start_the_camera_capture = 0;
volatile uint8_t frame_capture_complete = 0;  // Exported for main.c

typedef enum
{
    CAMERA_OK = 0x00,
    CAMERA_ERROR = 0x01,
    CAMERA_TIMEOUT = 0x02,
    CAMERA_NOT_DETECTED = 0x03,
    CAMERA_NOT_SUPPORTED = 0x04
} Camera_StatusTypeDef;

CAMERA_DrvTypeDef *camera_driv;
/* Camera module I2C HW address */
/* Image size */
uint32_t Im_size = 0;

__IO uint16_t pBuffer[QVGA_RES_X * QVGA_RES_Y];
HAL_StatusTypeDef hal_status = HAL_OK;

uint8_t CAMERA_Init(uint32_t Resolution) /*Camera initialization*/
{
    (void)Resolution;

    // TODO:

    return 0;
}

/**
 * @brief  CANERA power up
 * @retval None
 */
void CAMERA_PwrUp(void)
{
    GPIO_InitTypeDef gpio_init_structure;

    /* Enable GPIO clock */
    __HAL_RCC_GPIOH_CLK_ENABLE();

    /*** Configure the GPIO ***/
    /* Configure DCMI GPIO as alternate function */
    gpio_init_structure.Pin = GPIO_PIN_13;
    gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init_structure.Pull = GPIO_NOPULL;
    gpio_init_structure.Speed = GPIO_SPEED_HIGH;
    HAL_GPIO_Init(GPIOH, &gpio_init_structure);

    /* De-assert the camera POWER_DOWN pin (active high) */
    HAL_GPIO_WritePin(GPIOH, GPIO_PIN_13, GPIO_PIN_RESET);

    HAL_Delay(3); /* POWER_DOWN de-asserted during 3ms */
}

/**
 * @brief  CAMERA power down
 * @retval None
 */
void CAMERA_PwrDown(void)
{
    GPIO_InitTypeDef gpio_init_structure;

    /* Enable GPIO clock */
    __HAL_RCC_GPIOH_CLK_ENABLE();

    /*** Configure the GPIO ***/
    /* Configure DCMI GPIO as alternate function */
    gpio_init_structure.Pin = GPIO_PIN_13;
    gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init_structure.Pull = GPIO_NOPULL;
    gpio_init_structure.Speed = GPIO_SPEED_HIGH;
    HAL_GPIO_Init(GPIOH, &gpio_init_structure);

    /* Assert the camera POWER_DOWN pin (active high) */
    HAL_GPIO_WritePin(GPIOH, GPIO_PIN_13, GPIO_PIN_SET);
}

/*
static void test_ConvertLineRGB565ToARGB8888()
{
    // white/magenta test color pattern
    uint32_t offset_cam = 0;
    uint32_t offset_lcd = 0;

    for (uint32_t pos = 0; pos < LcdResX * LcdResY / 2; pos++)
    {
        uint32_t val = LCD_RGB565_COLOR_WHITE << 16 | LCD_RGB565_COLOR_DARKMAGENTA;
        *(__IO uint32_t *)(4 * pos + CAMERA_FRAME_BUFFER) = val;
    }

    for (uint32_t camera_line_nb = 0; camera_line_nb < CameraResY; camera_line_nb++)
    {
        LCD_LL_ConvertLineToARGB8888((uint32_t *)(CAMERA_FRAME_BUFFER + offset_cam),
                                     (uint32_t *)(LCD_FRAME_BUFFER + offset_lcd));

        offset_cam = offset_cam + (CameraResX * sizeof(uint16_t));
        offset_lcd = offset_lcd + (LcdResX * sizeof(uint32_t));
    }
}
*/

/**
 * @brief Map ImageFormat to OV5640 pixel format
 * @param format The ImageFormat enum value
 * @return OV5640 pixel format constant, or -1 if unsupported
 */
static int32_t map_format_to_ov5640(ImageFormat format)
{
    switch (format)
    {
    case IMAGE_FORMAT_GRAYSCALE:
        return OV5640_PIXEL_FORMAT_Y8;
    case IMAGE_FORMAT_RGB565:
        return OV5640_PIXEL_FORMAT_RGB565;
    case IMAGE_FORMAT_RGB888:
        return OV5640_PIXEL_FORMAT_RGB888;
    case IMAGE_FORMAT_YUV:
        return OV5640_PIXEL_FORMAT_YUV422;
    case IMAGE_FORMAT_HSI:
    case IMAGE_FORMAT_MASK:
    default:
        return -1;  // Unsupported format
    }
}

/**
 * @brief Validate if resolution is supported by OV5640
 * @param resolution The ImageResolution enum value
 * @return 0 if valid, -1 if unsupported
 */
static int validate_resolution(ImageResolution resolution)
{
    // OV5640 supports: QQVGA, QVGA, WQVGA, VGA
    switch (resolution)
    {
    case IMAGE_RES_QQVGA:  // 160x120
    case IMAGE_RES_QVGA:   // 320x240
    case IMAGE_RES_WQVGA:  // 480x272
    case IMAGE_RES_VGA:    // 640x480
        return 0;  // Valid
    default:
        return -1; // Unsupported resolution
    }
}

static int camera_init(ImageResolution resolution, ImageFormat format)
{
    // Validate resolution
    if (validate_resolution(resolution) != 0)
    {
        return -1;  // Invalid resolution
    }

    // Validate and map format
    int32_t ov5640_format = map_format_to_ov5640(format);
    if (ov5640_format < 0)
    {
        return -1;  // Invalid format
    }

#define IMAGE_RES_QQVGA 0
#define IMAGE_RES_QVGA 1
#define IMAGE_RES_WQVGA 2
#define IMAGE_RES_VGA 3

    CAMERA_PwrDown();
    // hal_status = BSP_SDRAM_Init();

    CAMERA_PwrUp();
    HAL_Delay(1000);

    // uint8_t status = CAMERA_ERROR;
    /* Read ID of Camera module via I2C */
    if (ov5640_ReadID(CAMERA_I2C_ADDRESS) == OV5640_ID)
    {
        camera_driv = &ov5640_drv;
        /* Initialize the camera driver structure */
        camera_driv->Init(CAMERA_I2C_ADDRESS, resolution);
        HAL_DCMI_DisableCROP(&hdcmi);
        HAL_Delay(500);

        // status = CAMERA_OK; /* Return CAMERA_OK status */
    }
    else
    {
        return -1;  // Camera not detected
    }

    // Set the validated pixel format (not hardcoded Y8 anymore)
    if (OV5640_SetPixelFormat(CAMERA_I2C_ADDRESS, (uint32_t)ov5640_format) != 0)
    {
        return -1;  // Failed to set pixel format
    }

    HAL_Delay(1000); // Delay for the camera to output correct data
    __HAL_DCMI_DISABLE_IT(&hdcmi, DCMI_IT_LINE | DCMI_IT_VSYNC);

    return 0;
}

static int camera_capture(captureMode mode, Image *inImg)
{
    // Clear the frame completion flag
    frame_capture_complete = 0;

    // Calculate DMA transfer size
    // DCMI DMA operates in 32-bit words
    // Total bytes = width × height × depth (depth: 1=GRAYSCALE, 2=RGB565, 3=RGB888)
    // DMA size in 32-bit words = total_bytes / 4
    uint32_t total_bytes = inImg->size * inImg->depth;
    uint32_t dma_size_words = total_bytes / 4;

    // Start DMA transfer
    HAL_DCMI_Start_DMA(&hdcmi, mode == CONTINUOUS ? DCMI_MODE_CONTINUOUS : DCMI_MODE_SNAPSHOT,
                       (uint32_t)inImg->pixels, dma_size_words);

    // For SINGLE mode, wait for frame completion
    if (mode == SINGLE) {
        uint32_t timeout = HAL_GetTick() + 5000;  // 5 second timeout
        while (!frame_capture_complete) {
            if (HAL_GetTick() > timeout) {
                HAL_DCMI_Stop(&hdcmi);
                return -1;  // Timeout error
            }
        }
    }

    // Set image data state to indicate raw pixel data is in the pixels buffer
    inImg->log = IMAGE_DATA_PIXELS;

    return 0;
}

static int camera_stop(void)
{
    HAL_DCMI_Stop(&hdcmi);
    return 0;
}

static int camera_setRes(ImageResolution resolution)
{
    // Validate resolution
    if (validate_resolution(resolution) != 0)
    {
        return -1;  // Invalid resolution
    }

    CAMERA_PwrDown();
    CAMERA_PwrUp();

    // uint8_t status = CAMERA_ERROR;
    /* Read ID of Camera module via I2C */
    if (ov5640_ReadID(CAMERA_I2C_ADDRESS) == OV5640_ID)
    {
        camera_driv = &ov5640_drv;
        /* Initialize the camera driver structure */
        camera_driv->Init(CAMERA_I2C_ADDRESS, resolution);
        HAL_DCMI_DisableCROP(&hdcmi);
        HAL_Delay(500);

        // status = CAMERA_OK; /* Return CAMERA_OK status */
    }
    else
    {
        return -1;  // Camera not detected
    }

    HAL_Delay(1000); // Delay for the camera to output correct data
    __HAL_DCMI_DISABLE_IT(&hdcmi, DCMI_IT_LINE | DCMI_IT_VSYNC);

    return 0;
}

camera_t stm32_ov5640 = {
    .init = camera_init,
    .capture = camera_capture,
    .stop = camera_stop,
    .setRes = camera_setRes};

/**
 * @brief DCMI frame event callback - called when a complete frame is captured
 */
void HAL_DCMI_FrameEventCallback(DCMI_HandleTypeDef *hdcmi)
{
    (void)hdcmi;
    frame_capture_complete = 1;
}

#endif