#include <embedDIP_configs.h>

#ifdef TARGET_BOARD_STM32F7

#include "device/serial/serial.h"
#include "stm32f7xx_hal.h"
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include "device/camera/camera.h"
#include "board/stm32f7/configs.h"

// Use the handles generated by STM32CubeMX
extern DCMI_HandleTypeDef hdcmi;
extern DMA2D_HandleTypeDef hdma2d;
extern I2C_HandleTypeDef hi2c3;
extern UART_HandleTypeDef huart1;

/* OV5640 I2C address
 * In STM32 HAL with 7-bit addressing mode, we still use the left-shifted address
 * The OV5640 has I2C slave address 0x3C (7-bit), which becomes 0x78 when left-shifted
 * HAL expects this left-shifted format even in 7-bit mode
 */
#define CAMERA_I2C_ADDRESS ((uint16_t)0x78)
#define OV5640_ID 0x5640

/* ========================================================================== */
/* I2C Wrapper Functions                                                      */
/* ========================================================================== */

/**
 * @brief  Initialize I2C for camera communication
 * @retval None
 */
static void CAMERA_IO_Init(void)
{
    /* I2C is already initialized by STM32CubeMX */
}

/**
 * @brief  Write a single byte to camera register
 * @param  Addr: Camera I2C address
 * @param  Reg: Register address (16-bit for OV5640)
 * @param  Value: Value to write
 * @retval HAL status
 */
static HAL_StatusTypeDef CAMERA_IO_Write(uint8_t Addr, uint16_t Reg, uint8_t Value)
{
    uint8_t buffer[3];

    /* OV5640 uses 16-bit register addresses */
    buffer[0] = (uint8_t)(Reg >> 8);     /* Register address high byte */
    buffer[1] = (uint8_t)(Reg & 0xFF);   /* Register address low byte */
    buffer[2] = Value;                    /* Data byte */

    return HAL_I2C_Master_Transmit(&hi2c3, Addr, buffer, 3, 1000);
}

/**
 * @brief  Read a single byte from camera register
 * @param  Addr: Camera I2C address
 * @param  Reg: Register address (16-bit for OV5640)
 * @retval Register value
 */
static uint8_t CAMERA_IO_Read(uint8_t Addr, uint16_t Reg)
{
    uint8_t read_value = 0;
    uint8_t reg_addr[2];

    /* OV5640 uses 16-bit register addresses */
    reg_addr[0] = (uint8_t)(Reg >> 8);
    reg_addr[1] = (uint8_t)(Reg & 0xFF);

    /* Write register address */
    HAL_I2C_Master_Transmit(&hi2c3, Addr, reg_addr, 2, 1000);

    /* Read register value */
    HAL_I2C_Master_Receive(&hi2c3, Addr, &read_value, 1, 1000);

    return read_value;
}

/**
 * @brief  Delay function for camera timing
 * @param  Delay: Delay in milliseconds
 * @retval None
 */
static void CAMERA_Delay(uint32_t Delay)
{
    HAL_Delay(Delay);
}

/**
 * @brief  OV5640 Registers
 */

/**
 * @brief  OV5640 Features Parameters
 */

/* Brightness */
#define OV5640_BRIGHTNESS_LEVEL4P 0x00 /* Brightness level +4         */
#define OV5640_BRIGHTNESS_LEVEL3P 0x01 /* Brightness level +3         */
#define OV5640_BRIGHTNESS_LEVEL2P 0x02 /* Brightness level +2         */
#define OV5640_BRIGHTNESS_LEVEL1P 0x04 /* Brightness level +1         */
#define OV5640_BRIGHTNESS_LEVEL0 0x08  /* Brightness level 0          */
#define OV5640_BRIGHTNESS_LEVEL1N 0x10 /* Brightness level -1         */
#define OV5640_BRIGHTNESS_LEVEL2N 0x20 /* Brightness level -2         */
#define OV5640_BRIGHTNESS_LEVEL3N 0x40 /* Brightness level -3         */
#define OV5640_BRIGHTNESS_LEVEL4N 0x80 /* Brightness level -4         */

/* Saturation */
#define OV5640_SATURATION_LEVEL4P 0x00 /* Saturation level +4         */
#define OV5640_SATURATION_LEVEL3P 0x01 /* Saturation level +3         */
#define OV5640_SATURATION_LEVEL2P 0x02 /* Saturation level +2         */
#define OV5640_SATURATION_LEVEL1P 0x04 /* Saturation level +1         */
#define OV5640_SATURATION_LEVEL0 0x08  /* Saturation level 0          */
#define OV5640_SATURATION_LEVEL1N 0x10 /* Saturation level -1         */
#define OV5640_SATURATION_LEVEL2N 0x20 /* Saturation level -2         */
#define OV5640_SATURATION_LEVEL3N 0x40 /* Saturation level -3         */
#define OV5640_SATURATION_LEVEL4N 0x80 /* Saturation level -4         */

/* Contrast */
#define OV5640_CONTRAST_LEVEL4P 0x00 /* Contrast level +4           */
#define OV5640_CONTRAST_LEVEL3P 0x01 /* Contrast level +3           */
#define OV5640_CONTRAST_LEVEL2P 0x02 /* Contrast level +2           */
#define OV5640_CONTRAST_LEVEL1P 0x04 /* Contrast level +1           */
#define OV5640_CONTRAST_LEVEL0 0x08  /* Contrast level 0            */
#define OV5640_CONTRAST_LEVEL1N 0x10 /* Contrast level -1           */
#define OV5640_CONTRAST_LEVEL2N 0x20 /* Contrast level -2           */
#define OV5640_CONTRAST_LEVEL3N 0x40 /* Contrast level -3           */
#define OV5640_CONTRAST_LEVEL4N 0x80 /* Contrast level -4           */

/* Hue Control */
#define OV5640_HUE_150P 0x0001 /* Hue 150+ degree           */
#define OV5640_HUE_120P 0x0002 /* Hue 120+ degree           */
#define OV5640_HUE_90P 0x0004  /* Hue 90+ degree            */
#define OV5640_HUE_60P 0x0008  /* Hue 60+ degree            */
#define OV5640_HUE_30P 0x0010  /* Hue 30+ degree            */
#define OV5640_HUE_0 0x0020    /* Hue 0 degree              */
#define OV5640_HUE_30N 0x0040  /* Hue 30- degree            */
#define OV5640_HUE_60N 0x0080  /* Hue 60- degree            */
#define OV5640_HUE_90N 0x0100  /* Hue 90- degree            */
#define OV5640_HUE_120N 0x0200 /* Hue 120- degree           */
#define OV5640_HUE_150N 0x0400 /* Hue 150- degree           */
#define OV5640_HUE_180N 0x0800 /* Hue 180- degree           */

/* Mirror/Flip */
#define OV5640_MIRROR 0x00             /* Set camera mirror config    */
#define OV5640_FLIP 0x01               /* Set camera flip config      */
#define OV5640_MIRROR_FLIP 0x02        /* Set camera mirror and flip  */
#define OV5640_MIRROR_FLIP_NORMAL 0x04 /* Set camera normal mode      */

/* Zoom */
#define OV5640_ZOOM_x8 0x00
#define OV5640_ZOOM_x4 0x11
#define OV5640_ZOOM_x2 0x22
#define OV5640_ZOOM_x1 0x44

/* Special Effect */
#define OV5640_COLOR_EFFECT_NONE 0x00         /* No effect               */
#define OV5640_COLOR_EFFECT_BLUE 0x01         /* Blue effect             */
#define OV5640_COLOR_EFFECT_RED 0x02          /* Red effect              */
#define OV5640_COLOR_EFFECT_GREEN 0x04        /* Green effect            */
#define OV5640_COLOR_EFFECT_BW 0x08           /* Black and White effect  */
#define OV5640_COLOR_EFFECT_SEPIA 0x10        /* Sepia effect            */
#define OV5640_COLOR_EFFECT_NEGATIVE 0x20     /* Negative effect         */
#define OV5640_COLOR_EFFECT_BW_NEGATIVE 0x40  /* BW Negative effect      */
#define OV5640_COLOR_EFFECT_OVEREXPOSURE 0x80 /* Over exposure effect    */
#define OV5640_COLOR_EFFECT_SOLARIZE 0x100    /* Solarized effect       */

/* Light Mode */
#define OV5640_LIGHT_AUTO 0x00   /* Light Mode Auto             */
#define OV5640_LIGHT_SUNNY 0x01  /* Light Mode Sunny            */
#define OV5640_LIGHT_OFFICE 0x02 /* Light Mode Office           */
#define OV5640_LIGHT_HOME 0x04   /* Light Mode Home             */
#define OV5640_LIGHT_CLOUDY 0x08 /* Light Mode Claudy           */

/* Saturation */
#define OV5640_SATURATION_0 0x00 /* Color saturation 0          */
#define OV5640_SATURATION_1 0x01 /* Color saturation 1          */
#define OV5640_SATURATION_2 0x02 /* Color saturation 2          */
#define OV5640_SATURATION_3 0x04 /* Color saturation 3          */

/* Exposure */
#define OV5640_EXPOSURE_LEVEL_0 0x00 /* Exposure Level 0            */
#define OV5640_EXPOSURE_LEVEL_1 0x01 /* Exposure Level 1            */
#define OV5640_EXPOSURE_LEVEL_2 0x02 /* Exposure Level 2            */
#define OV5640_EXPOSURE_LEVEL_3 0x04 /* Exposure Level 3            */

static uint32_t ov5640_ConvertValue(uint32_t feature, uint32_t value);

/* OV5640 Light Mode setting */
const uint16_t OV5640_LightModeAuto[][2] =
    {
        {0x3406, 0x00},
        {0x3400, 0x04},
        {0x3401, 0x00},
        {0x3402, 0x04},
        {0x3403, 0x00},
        {0x3404, 0x04},
        {0x3405, 0x00},
};

const uint16_t OV5640_LightModeCloudy[][2] =
    {
        {0x3406, 0x01},
        {0x3400, 0x06},
        {0x3401, 0x48},
        {0x3402, 0x04},
        {0x3403, 0x00},
        {0x3404, 0x04},
        {0x3405, 0xd3},
};

const uint16_t OV5640_LightModeOffice[][2] =
    {
        {0x3406, 0x01},
        {0x3400, 0x05},
        {0x3401, 0x48},
        {0x3402, 0x04},
        {0x3403, 0x00},
        {0x3404, 0x07},
        {0x3405, 0xcf},
};

const uint16_t OV5640_LightModeHome[][2] =
    {
        {0x3406, 0x01},
        {0x3400, 0x04},
        {0x3401, 0x10},
        {0x3402, 0x04},
        {0x3403, 0x00},
        {0x3404, 0x08},
        {0x3405, 0xB6},
};

const uint16_t OV5640_LightModeSunny[][2] =
    {
        {0x3406, 0x01},
        {0x3400, 0x06},
        {0x3401, 0x1c},
        {0x3402, 0x04},
        {0x3403, 0x00},
        {0x3404, 0x04},
        {0x3405, 0xf3},
};

/**
 * @brief  Set the OV5640 camera Light Mode.
 * @param  DeviceAddr : Device address on communication Bus.
 * @param  Effect : Effect to be configured
 * @retval None
 */
void OV5640_SetLightMode(uint16_t DeviceAddr, uint8_t LightMode)
{
    uint32_t index = 0;

    CAMERA_IO_Write(DeviceAddr, 0x3406, 0x00);
    CAMERA_IO_Write(DeviceAddr, 0x5190, 0x46);
    CAMERA_IO_Write(DeviceAddr, 0x5191, 0xf8);
    CAMERA_IO_Write(DeviceAddr, 0x5192, 0x04);

    switch (LightMode)
    {
    case OV5640_LIGHT_AUTO:
        for (index = 0; index < (sizeof(OV5640_LightModeAuto) / 4); index++)
        {
            CAMERA_IO_Write(DeviceAddr, OV5640_LightModeAuto[index][0], OV5640_LightModeAuto[index][1]);
        }
        break;
    case OV5640_LIGHT_SUNNY:
        for (index = 0; index < (sizeof(OV5640_LightModeSunny) / 4); index++)
        {
            CAMERA_IO_Write(DeviceAddr, OV5640_LightModeSunny[index][0], OV5640_LightModeSunny[index][1]);
        }
        break;
    case OV5640_LIGHT_OFFICE:
        for (index = 0; index < (sizeof(OV5640_LightModeOffice) / 4); index++)
        {
            CAMERA_IO_Write(DeviceAddr, OV5640_LightModeOffice[index][0], OV5640_LightModeOffice[index][1]);
        }
        break;
    case OV5640_LIGHT_CLOUDY:
        for (index = 0; index < (sizeof(OV5640_LightModeCloudy) / 4); index++)
        {
            CAMERA_IO_Write(DeviceAddr, OV5640_LightModeCloudy[index][0], OV5640_LightModeCloudy[index][1]);
        }
        break;
    case OV5640_LIGHT_HOME:
        for (index = 0; index < (sizeof(OV5640_LightModeHome) / 4); index++)
        {
            CAMERA_IO_Write(DeviceAddr, OV5640_LightModeHome[index][0], OV5640_LightModeHome[index][1]);
        }
        break;
    default:
        /* Auto light mode used */
        for (index = 0; index < (sizeof(OV5640_LightModeAuto) / 4); index++)
        {
            CAMERA_IO_Write(DeviceAddr, OV5640_LightModeAuto[index][0], OV5640_LightModeAuto[index][1]);
        }
        break;
    }
}

/**
 * @brief  Set the OV5640 camera Special Effect.
 * @param  DeviceAddr: Device address on communication Bus.
 * @param  Effect: Effect to be configured
 * @retval None
 */
void OV5640_SetEffect(uint16_t DeviceAddr, uint32_t Effect)
{
    switch (Effect)
    {
    case OV5640_COLOR_EFFECT_NONE:
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0x7F);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x00);
        break;

    case OV5640_COLOR_EFFECT_BLUE:
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x18);
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0xA0);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x40);
        break;

    case OV5640_COLOR_EFFECT_RED:
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x18);
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x80);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0xC0);
        break;

    case OV5640_COLOR_EFFECT_GREEN:
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x18);
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x60);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x60);
        break;

    case OV5640_COLOR_EFFECT_BW:
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x18);
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x80);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x80);
        break;

    case OV5640_COLOR_EFFECT_SEPIA:
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x18);
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0xA0);
        break;

    case OV5640_COLOR_EFFECT_NEGATIVE:
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x40);
        break;

    case OV5640_COLOR_EFFECT_BW_NEGATIVE:
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x58);
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x40);
        break;

    case OV5640_COLOR_EFFECT_OVEREXPOSURE:
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x18);
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0xF0);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0xF0);
        break;

    case OV5640_COLOR_EFFECT_SOLARIZE:
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x06);
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x10);
        CAMERA_IO_Write(DeviceAddr, 0x5003, 0x09);
        break;

    default:
        /* No effect */
        CAMERA_IO_Write(DeviceAddr, 0x5001, 0x7F);
        CAMERA_IO_Write(DeviceAddr, 0x5580, 0x00);
        break;
    }
}

/**
 * @brief  Set the OV5640 camera Brightness Level.
 * @note   The brightness of OV5640 could be adjusted. Higher brightness will
 *         make the picture more bright. The side effect of higher brightness
 *         is the picture looks foggy.
 * @param  DeviceAddr: Device address on communication Bus.
 * @param  Level: Value to be configured
 * @retval None
 */
void OV5640_SetBrightness(uint16_t DeviceAddr, uint8_t Level)
{
    CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);

    switch (Level)
    {
    case OV5640_BRIGHTNESS_LEVEL4P:
        CAMERA_IO_Write(DeviceAddr, 0x5587, 0x40);
        break;

    case OV5640_BRIGHTNESS_LEVEL3P:
        CAMERA_IO_Write(DeviceAddr, 0x5587, 0x30);
        break;

    case OV5640_BRIGHTNESS_LEVEL2P:
        CAMERA_IO_Write(DeviceAddr, 0x5587, 0x20);
        break;

    case OV5640_BRIGHTNESS_LEVEL1P:
        CAMERA_IO_Write(DeviceAddr, 0x5587, 0x10);
        break;

    case OV5640_BRIGHTNESS_LEVEL0:
        CAMERA_IO_Write(DeviceAddr, 0x5587, 0x00);
        break;

    case OV5640_BRIGHTNESS_LEVEL1N:
        CAMERA_IO_Write(DeviceAddr, 0x5587, 0x10);
        break;

    case OV5640_BRIGHTNESS_LEVEL2N:
        CAMERA_IO_Write(DeviceAddr, 0x5587, 0x20);
        break;

    case OV5640_BRIGHTNESS_LEVEL3N:
        CAMERA_IO_Write(DeviceAddr, 0x5587, 0x30);
        break;

    case OV5640_BRIGHTNESS_LEVEL4N:
        CAMERA_IO_Write(DeviceAddr, 0x5587, 0x40);
        break;

    default:
        /* Level 0 as default */
        Level = OV5640_BRIGHTNESS_LEVEL0;
        CAMERA_IO_Write(DeviceAddr, 0x5587, 0x00);
        break;
    }

    CAMERA_IO_Write(DeviceAddr, 0x5580, 0x04);

    if (Level < OV5640_SATURATION_LEVEL1N)
    {
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x01);
    }
    else
    {
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x09);
    }
}

/**
 * @brief  Set the OV5640 camera Saturation Level.
 * @note   The color saturation of OV5640 could be adjusted. High color saturation
 *         would make the picture looks more vivid, but the side effect is the
 *         bigger noise and not accurate skin color.
 * @param  DeviceAddr: Device address on communication Bus.
 * @param  Level: Value to be configured
 * @retval None
 */
void OV5640_SetSaturation(uint16_t DeviceAddr, uint8_t Level)
{
    CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);

    switch (Level)
    {
    case OV5640_SATURATION_LEVEL4P:
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x40);
        break;

    case OV5640_SATURATION_LEVEL3P:
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x50);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x50);
        break;

    case OV5640_SATURATION_LEVEL2P:
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x60);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x60);
        break;

    case OV5640_SATURATION_LEVEL1P:
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x70);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x70);
        break;

    case OV5640_SATURATION_LEVEL0:
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x80);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x80);
        break;

    case OV5640_SATURATION_LEVEL1N:
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x30);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x30);
        break;

    case OV5640_SATURATION_LEVEL2N:
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x20);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x20);
        break;

    case OV5640_SATURATION_LEVEL3N:
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x10);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x10);
        break;

    case OV5640_SATURATION_LEVEL4N:
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x00);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x00);
        break;

    default:
        /* Level 0 as default */
        CAMERA_IO_Write(DeviceAddr, 0x5583, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5584, 0x40);
        break;
    }

    CAMERA_IO_Write(DeviceAddr, 0x5580, 0x02);
    CAMERA_IO_Write(DeviceAddr, 0x5588, 0x41);
}

/**
 * @brief  Set the OV5640 camera Contrast Level.
 * @note   The contrast of OV5640 could be adjusted. Higher contrast will make
 *         the picture sharp. But the side effect is loosing dynamic range.
 * @param  DeviceAddr: Device address on communication Bus.
 * @param  Level: Value to be configured
 * @retval None
 */
void OV5640_SetContrast(uint16_t DeviceAddr, uint8_t Level)
{
    CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
    CAMERA_IO_Write(DeviceAddr, 0x5580, 0x04);

    switch (Level)
    {
    case OV5640_CONTRAST_LEVEL4P:
        CAMERA_IO_Write(DeviceAddr, 0x5586, 0x30);
        CAMERA_IO_Write(DeviceAddr, 0x5585, 0x30);
        break;

    case OV5640_CONTRAST_LEVEL3P:
        CAMERA_IO_Write(DeviceAddr, 0x5586, 0x2C);
        CAMERA_IO_Write(DeviceAddr, 0x5585, 0x2C);
        break;

    case OV5640_CONTRAST_LEVEL2P:
        CAMERA_IO_Write(DeviceAddr, 0x5586, 0x28);
        CAMERA_IO_Write(DeviceAddr, 0x5585, 0x28);
        break;

    case OV5640_CONTRAST_LEVEL1P:
        CAMERA_IO_Write(DeviceAddr, 0x5586, 0x24);
        CAMERA_IO_Write(DeviceAddr, 0x5585, 0x24);
        break;

    case OV5640_CONTRAST_LEVEL0:
        CAMERA_IO_Write(DeviceAddr, 0x5586, 0x20);
        CAMERA_IO_Write(DeviceAddr, 0x5585, 0x20);
        break;

    case OV5640_CONTRAST_LEVEL1N:
        CAMERA_IO_Write(DeviceAddr, 0x5586, 0x1C);
        CAMERA_IO_Write(DeviceAddr, 0x5585, 0x1C);
        break;

    case OV5640_CONTRAST_LEVEL2N:
        CAMERA_IO_Write(DeviceAddr, 0x5586, 0x18);
        CAMERA_IO_Write(DeviceAddr, 0x5585, 0x18);
        break;

    case OV5640_CONTRAST_LEVEL3N:
        CAMERA_IO_Write(DeviceAddr, 0x5586, 0x14);
        CAMERA_IO_Write(DeviceAddr, 0x5585, 0x14);
        break;

    case OV5640_CONTRAST_LEVEL4N:
        CAMERA_IO_Write(DeviceAddr, 0x5586, 0x10);
        CAMERA_IO_Write(DeviceAddr, 0x5585, 0x10);
        break;

    default:
        /* Level 0 as default */
        CAMERA_IO_Write(DeviceAddr, 0x5586, 0x20);
        CAMERA_IO_Write(DeviceAddr, 0x5585, 0x20);
        break;
    }

    CAMERA_IO_Write(DeviceAddr, 0x5588, 0x41);
}

/**
 * @brief  Set the OV5640 camera Contrast Level.
 * @note   The contrast of OV5640 could be adjusted. Higher contrast will make
 *         the picture sharp. But the side effect is loosing dynamic range.
 * @param  DeviceAddr: Device address on communication Bus.
 * @param  Level: Value to be configured
 * @retval None
 */
void OV5640_SetPixelFormat(uint16_t DeviceAddr, uint8_t Level)
{
    (void)DeviceAddr;
    (void)Level;

    // TODO: Implement pixel format setting
}

/**
 * @brief  Set the OV5640 camera Hue degree.
 * @param  DeviceAddr: Device address on communication Bus.
 * @param  Level: Value to be configured
 * @retval None
 */
void OV5640_SetHueDegree(uint16_t DeviceAddr, uint16_t Degree)
{
    CAMERA_IO_Write(DeviceAddr, 0x5001, 0xFF);
    CAMERA_IO_Write(DeviceAddr, 0x5580, 0x01);

    switch (Degree)
    {
    case OV5640_HUE_150P:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x6F);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x31);
        break;

    case OV5640_HUE_120P:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x6F);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x31);
        break;

    case OV5640_HUE_90P:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x00);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x80);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x31);
        break;

    case OV5640_HUE_60P:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x6F);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x01);
        break;

    case OV5640_HUE_30P:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x6F);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x01);
        break;

    case OV5640_HUE_0:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x80);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x00);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x01);
        break;

    case OV5640_HUE_30N:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x6F);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x02);
        break;

    case OV5640_HUE_60N:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x6F);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x02);
        break;

    case OV5640_HUE_90N:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x00);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x80);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x02);
        break;

    case OV5640_HUE_120N:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x6F);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x32);
        break;

    case OV5640_HUE_150N:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x6F);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x40);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x32);
        break;

    case OV5640_HUE_180N:
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x80);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x00);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x32);
        break;

    default:
        /* Hue degree 0 as default */
        CAMERA_IO_Write(DeviceAddr, 0x5581, 0x80);
        CAMERA_IO_Write(DeviceAddr, 0x5582, 0x00);
        CAMERA_IO_Write(DeviceAddr, 0x5588, 0x01);
        break;
    }
}

/**
 * @brief  Control OV5640 camera mirror/vflip.
 * @param  DeviceAddr: Device address on communication Bus.
 * @param  Config: To configure mirror, flip, both or nothing
 * @retval None
 */
void OV5640_MirrorFlipConfig(uint16_t DeviceAddr, uint8_t Config)
{
    uint8_t tmp3820 = 0, tmp3821;

    tmp3820 = CAMERA_IO_Read(DeviceAddr, 0x3820);
    tmp3820 &= 0xF9;
    tmp3821 = CAMERA_IO_Read(DeviceAddr, 0x3821);
    tmp3821 &= 0xF9;

    switch (Config)
    {
    case OV5640_MIRROR:
        CAMERA_IO_Write(DeviceAddr, 0x3820, tmp3820 | 0x00);
        CAMERA_IO_Write(DeviceAddr, 0x3821, tmp3821 | 0x06);
        break;

    case OV5640_FLIP:
        CAMERA_IO_Write(DeviceAddr, 0x3820, tmp3820 | 0x06);
        CAMERA_IO_Write(DeviceAddr, 0x3821, tmp3821 | 0x00);
        break;
    case OV5640_MIRROR_FLIP:
        CAMERA_IO_Write(DeviceAddr, 0x3820, tmp3820 | 0x06);
        CAMERA_IO_Write(DeviceAddr, 0x3821, tmp3821 | 0x06);
        break;

    case OV5640_MIRROR_FLIP_NORMAL:
        CAMERA_IO_Write(DeviceAddr, 0x3820, tmp3820 | 0x00);
        CAMERA_IO_Write(DeviceAddr, 0x3821, tmp3821 | 0x06);
        break;

    default:
        CAMERA_IO_Write(DeviceAddr, 0x3820, tmp3820 | 0x00);
        CAMERA_IO_Write(DeviceAddr, 0x3821, tmp3821 | 0x00);
        break;
    }
}

/**
 * @brief  Get OV5640 camera resolution.
 * @param  DeviceAddr: Device address on communication Bus.
 * @retval Camera resolution else 0xFF
 */
int32_t OV5640_GetResolution(uint16_t DeviceAddr)
{
    uint16_t x_size = 0, y_size = 0;
    int32_t res = CAMERA_R640x480;

    x_size = CAMERA_IO_Read(DeviceAddr, 0x3808) << 8;
    x_size |= CAMERA_IO_Read(DeviceAddr, 0x3809);
    y_size = CAMERA_IO_Read(DeviceAddr, 0x380A) << 8;
    y_size |= CAMERA_IO_Read(DeviceAddr, 0x380B);

    if ((x_size == 640) && (y_size == 480))
    {
        res = CAMERA_R640x480;
    }
    else if ((x_size == 480) && (y_size == 272))
    {
        res = CAMERA_R480x272;
    }
    else if ((x_size == 320) && (y_size == 240))
    {
        res = CAMERA_R320x240;
    }
    else if ((x_size == 160) && (y_size == 120))
    {
        res = CAMERA_R160x120;
    }
    else
    {
        res = 0xFF;
    }
    return res;
}

/**
 * @brief  Control OV5640 camera mirror/vflip.
 * @param  DeviceAddr: Device address on communication Bus.
 * @param  Zoom: Zoom to be configured
 * @retval None
 */
void OV5640_ZoomConfig(uint16_t DeviceAddr, uint8_t Zoom)
{
    int32_t res = 0;

    /* Get camera resolution */
    res = OV5640_GetResolution(DeviceAddr);

    if (Zoom == OV5640_ZOOM_x1)
    {
        CAMERA_IO_Write(DeviceAddr, 0x5600, 0x10);
    }
    else
    {
        switch (res)
        {
        case CAMERA_R320x240:
        case CAMERA_R480x272:
            Zoom = Zoom >> 1;
            break;
        case CAMERA_R640x480:
            Zoom = Zoom >> 2;
            break;
        default:
            break;
        }

        CAMERA_IO_Write(DeviceAddr, 0x5600, 0x00);
        CAMERA_IO_Write(DeviceAddr, 0x5601, Zoom);
    }
}

/******************************************************************************
                            Static Functions
*******************************************************************************/
/**
 * @brief  Convert input values into ov5640 parameters.
 * @param  feature: Camera feature to be configured
 * @param  value: Value to be configured
 * @retval The converted value
 */
static uint32_t ov5640_ConvertValue(uint32_t feature, uint32_t value)
{
    uint32_t ret = 0;

    switch (feature)
    {
    case CAMERA_BLACK_WHITE:
    {
        switch (value)
        {
        case CAMERA_BLACK_WHITE_BW:
        {
            ret = OV5640_COLOR_EFFECT_BW;
            break;
        }
        case CAMERA_BLACK_WHITE_NEGATIVE:
        {
            ret = OV5640_COLOR_EFFECT_NEGATIVE;
            break;
        }
        case CAMERA_BLACK_WHITE_BW_NEGATIVE:
        {
            ret = OV5640_COLOR_EFFECT_BW_NEGATIVE;
            break;
        }
        case CAMERA_BLACK_WHITE_NORMAL:
        default:
        {
            ret = OV5640_COLOR_EFFECT_NONE;
            break;
        }
        }
        break;
    }
    case CAMERA_CONTRAST_BRIGHTNESS:
    {
        switch (value)
        {
        case CAMERA_BRIGHTNESS_LEVEL0:
        {
            ret = OV5640_BRIGHTNESS_LEVEL4N;
            break;
        }
        case CAMERA_BRIGHTNESS_LEVEL1:
        {
            ret = OV5640_BRIGHTNESS_LEVEL2N;
            break;
        }
        case CAMERA_BRIGHTNESS_LEVEL2:
        {
            ret = OV5640_BRIGHTNESS_LEVEL0;
            break;
        }
        case CAMERA_BRIGHTNESS_LEVEL3:
        {
            ret = OV5640_BRIGHTNESS_LEVEL2P;
            break;
        }
        case CAMERA_BRIGHTNESS_LEVEL4:
        {
            ret = OV5640_BRIGHTNESS_LEVEL4P;
            break;
        }
        case CAMERA_CONTRAST_LEVEL0:
        {
            ret = OV5640_CONTRAST_LEVEL4N;
            break;
        }
        case CAMERA_CONTRAST_LEVEL1:
        {
            ret = OV5640_CONTRAST_LEVEL2N;
            break;
        }
        case CAMERA_CONTRAST_LEVEL2:
        {
            ret = OV5640_CONTRAST_LEVEL0;
            break;
        }
        case CAMERA_CONTRAST_LEVEL3:
        {
            ret = OV5640_CONTRAST_LEVEL2P;
            break;
        }
        case CAMERA_CONTRAST_LEVEL4:
        {
            ret = OV5640_CONTRAST_LEVEL4P;
            break;
        }
        default:
        {
            ret = OV5640_CONTRAST_LEVEL0;
            break;
        }
        }
        break;
    }
    case CAMERA_COLOR_EFFECT:
    {
        switch (value)
        {
        case CAMERA_COLOR_EFFECT_ANTIQUE:
        {
            ret = OV5640_COLOR_EFFECT_SEPIA;
            break;
        }
        case CAMERA_COLOR_EFFECT_BLUE:
        {
            ret = OV5640_COLOR_EFFECT_BLUE;
            break;
        }
        case CAMERA_COLOR_EFFECT_GREEN:
        {
            ret = OV5640_COLOR_EFFECT_GREEN;
            break;
        }
        case CAMERA_COLOR_EFFECT_RED:
        {
            ret = OV5640_COLOR_EFFECT_RED;
            break;
        }
        case CAMERA_COLOR_EFFECT_NONE:
        default:
        {
            ret = OV5640_COLOR_EFFECT_NONE;
            break;
        }
        }
        break;
    default:
    {
        ret = 0;
        break;
    }
    }
    }

    return ret;
}

/**
 * @brief  Read the OV5640 Camera identity.
 * @param  DeviceAddr: Device address on communication Bus.
 * @retval the OV5640 ID
 */
uint16_t ov5640_ReadID(uint16_t DeviceAddr)
{
    uint16_t read_val = 0;

    /* Initialize I2C */
    CAMERA_IO_Init();

    /* Prepare the camera to be configured */
    CAMERA_IO_Write(DeviceAddr, 0x3008, 0x80);
    CAMERA_Delay(500);

    read_val = CAMERA_IO_Read(DeviceAddr, 0x300A);
    read_val = read_val << 8;
    read_val |= CAMERA_IO_Read(DeviceAddr, 0x300B);
    /* Get the camera ID */
    return read_val;
}

/**
 * @brief  Configures the OV5640 camera feature.
 * @param  DeviceAddr: Device address on communication Bus.
 * @param  feature: Camera feature to be configured
 * @param  value: Value to be configured
 * @param  brightness_value: Brightness value to be configured
 * @retval None
 */
void ov5640_Config(uint16_t DeviceAddr, uint32_t feature, uint32_t value, uint32_t brightness_value)
{
    uint32_t value_tmp;
    uint32_t br_value;

    /* Convert the input value into ov5640 parameters */
    value_tmp = ov5640_ConvertValue(feature, value);
    br_value = ov5640_ConvertValue(CAMERA_CONTRAST_BRIGHTNESS, brightness_value);

    switch (feature)
    {
    case CAMERA_CONTRAST_BRIGHTNESS:
    {
        OV5640_SetContrast(DeviceAddr, value_tmp);
        OV5640_SetBrightness(DeviceAddr, br_value);
        break;
    }
    case CAMERA_BLACK_WHITE:
    case CAMERA_COLOR_EFFECT:
    {
        OV5640_SetEffect(DeviceAddr, value_tmp);
        break;
    }
    default:
    {
        break;
    }
    }
}

const uint16_t OV5640_Init[][2] =
    {
        {0x3103, 0x11},
        {0x3008, 0x82},
        {0x3103, 0x03},
        {0x3017, 0xFF},
        {0x3018, 0xf3},
        {0x3034, 0x18},
        {0x3008, 0x02},
        {0x3035, 0x41},
        {0x3036, 0x60},
        {0x3037, 0x13},
        {0x3108, 0x01},
        {0x3630, 0x36},
        {0x3631, 0x0e},
        {0x3632, 0xe2},
        {0x3633, 0x12},
        {0x3621, 0xe0},
        {0x3704, 0xa0},
        {0x3703, 0x5a},
        {0x3715, 0x78},
        {0x3717, 0x01},
        {0x370b, 0x60},
        {0x3705, 0x1a},
        {0x3905, 0x02},
        {0x3906, 0x10},
        {0x3901, 0x0a},
        {0x3731, 0x12},
        {0x3600, 0x08},
        {0x3601, 0x33},
        {0x302d, 0x60},
        {0x3620, 0x52},
        {0x371b, 0x20},
        {0x471c, 0x50},
        {0x3a13, 0x43},
        {0x3a18, 0x00},
        {0x3a19, 0xf8},
        {0x3635, 0x13},
        {0x3636, 0x03},
        {0x3634, 0x40},
        {0x3622, 0x01},
        {0x3c01, 0x34},
        {0x3c04, 0x28},
        {0x3c05, 0x98},
        {0x3c06, 0x00},
        {0x3c07, 0x00},
        {0x3c08, 0x01},
        {0x3c09, 0x2c},
        {0x3c0a, 0x9c},
        {0x3c0b, 0x40},
        {0x3820, 0x00},
        {0x3821, 0x06},
        {0x3814, 0x31},
        {0x3815, 0x31},
        {0x3800, 0x00},
        {0x3801, 0x00},
        {0x3802, 0x00},
        {0x3803, 0x04},
        {0x3804, 0x0a},
        {0x3805, 0x3f},
        {0x3806, 0x07},
        {0x3807, 0x9b},
        {0x3808, 0x03},
        {0x3809, 0x20},
        {0x380a, 0x02},
        {0x380b, 0x58},
        {0x380c, 0x07},
        {0x380d, 0x68},
        {0x380e, 0x03},
        {0x380f, 0xd8},
        {0x3810, 0x00},
        {0x3811, 0x10},
        {0x3812, 0x00},
        {0x3813, 0x06},
        {0x3618, 0x00},
        {0x3612, 0x29},
        {0x3708, 0x64},
        {0x3709, 0x52},
        {0x370c, 0x03},
        {0x3a02, 0x03},
        {0x3a03, 0xd8},
        {0x3a08, 0x01},
        {0x3a09, 0x27},
        {0x3a0a, 0x00},
        {0x3a0b, 0xf6},
        {0x3a0e, 0x03},
        {0x3a0d, 0x04},
        {0x3a14, 0x03},
        {0x3a15, 0xd8},
        {0x4001, 0x02},
        {0x4004, 0x02},
        {0x3000, 0x00},
        {0x3002, 0x1c},
        {0x3004, 0xff},
        {0x3006, 0xc3},
        {0x300e, 0x58},
        {0x302e, 0x00},
        {0x4740, 0x20},
        {0x4300, 0x30},
        {0x501f, 0x00},
        {0x4713, 0x03},
        {0x4407, 0x04},
        {0x440e, 0x00},
        {0x460b, 0x35},
        {0x460c, 0x23},
        {0x4837, 0x22},
        {0x3824, 0x02},
        {0x5000, 0xa7},
        {0x5001, 0xa3},
        {0x5180, 0xff},
        {0x5181, 0xf2},
        {0x5182, 0x00},
        {0x5183, 0x14},
        {0x5184, 0x25},
        {0x5185, 0x24},
        {0x5186, 0x09},
        {0x5187, 0x09},
        {0x5188, 0x09},
        {0x5189, 0x75},
        {0x518a, 0x54},
        {0x518b, 0xe0},
        {0x518c, 0xb2},
        {0x518d, 0x42},
        {0x518e, 0x3d},
        {0x518f, 0x56},
        {0x5190, 0x46},
        {0x5191, 0xf8},
        {0x5192, 0x04},
        {0x5193, 0x70},
        {0x5194, 0xf0},
        {0x5195, 0xf0},
        {0x5196, 0x03},
        {0x5197, 0x01},
        {0x5198, 0x04},
        {0x5199, 0x12},
        {0x519a, 0x04},
        {0x519b, 0x00},
        {0x519c, 0x06},
        {0x519d, 0x82},
        {0x519e, 0x38},
        {0x5381, 0x1e},
        {0x5382, 0x5b},
        {0x5383, 0x08},
        {0x5384, 0x0a},
        {0x5385, 0x7e},
        {0x5386, 0x88},
        {0x5387, 0x7c},
        {0x5388, 0x6c},
        {0x5389, 0x10},
        {0x538a, 0x01},
        {0x538b, 0x98},
        {0x5300, 0x08},
        {0x5301, 0x30},
        {0x5302, 0x10},
        {0x5303, 0x00},
        {0x5304, 0x08},
        {0x5305, 0x30},
        {0x5306, 0x08},
        {0x5307, 0x16},
        {0x5309, 0x08},
        {0x530a, 0x30},
        {0x530b, 0x04},
        {0x530c, 0x06},
        {0x5480, 0x01},
        {0x5481, 0x08},
        {0x5482, 0x14},
        {0x5483, 0x28},
        {0x5484, 0x51},
        {0x5485, 0x65},
        {0x5486, 0x71},
        {0x5487, 0x7d},
        {0x5488, 0x87},
        {0x5489, 0x91},
        {0x548a, 0x9a},
        {0x548b, 0xaa},
        {0x548c, 0xb8},
        {0x548d, 0xcd},
        {0x548e, 0xdd},
        {0x548f, 0xea},
        {0x5490, 0x1d},
        {0x5580, 0x02},
        {0x5583, 0x40},
        {0x5584, 0x10},
        {0x5589, 0x10},
        {0x558a, 0x00},
        {0x558b, 0xf8},
        {0x5800, 0x23},
        {0x5801, 0x14},
        {0x5802, 0x0f},
        {0x5803, 0x0f},
        {0x5804, 0x12},
        {0x5805, 0x26},
        {0x5806, 0x0c},
        {0x5807, 0x08},
        {0x5808, 0x05},
        {0x5809, 0x05},
        {0x580a, 0x08},
        {0x580b, 0x0d},
        {0x580c, 0x08},
        {0x580d, 0x03},
        {0x580e, 0x00},
        {0x580f, 0x00},
        {0x5810, 0x03},
        {0x5811, 0x09},
        {0x5812, 0x07},
        {0x5813, 0x03},
        {0x5814, 0x00},
        {0x5815, 0x01},
        {0x5816, 0x03},
        {0x5817, 0x08},
        {0x5818, 0x0d},
        {0x5819, 0x08},
        {0x581a, 0x05},
        {0x581b, 0x06},
        {0x581c, 0x08},
        {0x581d, 0x0e},
        {0x581e, 0x29},
        {0x581f, 0x17},
        {0x5820, 0x11},
        {0x5821, 0x11},
        {0x5822, 0x15},
        {0x5823, 0x28},
        {0x5824, 0x46},
        {0x5825, 0x26},
        {0x5826, 0x08},
        {0x5827, 0x26},
        {0x5828, 0x64},
        {0x5829, 0x26},
        {0x582a, 0x24},
        {0x582b, 0x22},
        {0x582c, 0x24},
        {0x582d, 0x24},
        {0x582e, 0x06},
        {0x582f, 0x22},
        {0x5830, 0x40},
        {0x5831, 0x42},
        {0x5832, 0x24},
        {0x5833, 0x26},
        {0x5834, 0x24},
        {0x5835, 0x22},
        {0x5836, 0x22},
        {0x5837, 0x26},
        {0x5838, 0x44},
        {0x5839, 0x24},
        {0x583a, 0x26},
        {0x583b, 0x28},
        {0x583c, 0x42},
        {0x583d, 0xce},
        {0x5025, 0x00},
        {0x3a0f, 0x30},
        {0x3a10, 0x28},
        {0x3a1b, 0x30},
        {0x3a1e, 0x26},
        {0x3a11, 0x60},
        {0x3a1f, 0x14},
        {0x3008, 0x02},
};

/* Initialization sequence for WVGA resolution (800x480)*/
const uint16_t OV5640_WVGA[][2] =
    {
        {0x3808, 0x03},
        {0x3809, 0x20},
        {0x380a, 0x01},
        {0x380b, 0xE0},
        {0x4300, 0x6F},
        {0x4740, 0x22},
        {0x501F, 0x01},
};

/* Initialization sequence for VGA resolution (640x480)*/
const uint16_t OV5640_VGA[][2] =
    {
        {0x3808, 0x02},
        {0x3809, 0x80},
        {0x380a, 0x01},
        {0x380b, 0xE0},
        {0x4300, 0x6F},
        {0x4740, 0x22},
        {0x501F, 0x01},
};

/* Initialization sequence for 480x272 resolution */
const uint16_t OV5640_480x272[][2] =
    {
        {0x3808, 0x01},
        {0x3809, 0xE0},
        {0x380a, 0x01},
        {0x380b, 0x10},
        //{0x4300, 0x10},// 0x6F for RGB
        //{0x4300, 0x23}, //rgb 888
        {0x4300, 0x6F}, // rgb 565
        {0x4740, 0x22},
        //{0x501f, 0x00},// 0x01 for RGB 0x00 for Grayscale
        {0x501f, 0x01}, // 0x01 for RGB
};

const uint16_t OV5640_QVGA[][2] =
    {
        {0x3808, 0x01},
        {0x3809, 0x40},
        {0x380a, 0x00},
        {0x380b, 0xF0},
        {0x4300, 0x6F},
        {0x4740, 0x22},
        {0x501f, 0x01},
};

/* Initialization sequence for QQVGA resolution (160x120) */
const uint16_t OV5640_QQVGA[][2] =
    {
        {0x3808, 0x00},
        {0x3809, 0xA0},
        {0x380a, 0x00},
        {0x380b, 0x78},
        //{0x4300, 0x10},// 0x6F for RGB
        //{0x4300, 0x23}, //rgb 888
        {0x4300, 0x6F}, // rgb 565
        {0x4740, 0x22},
        //{0x501f, 0x00},// 0x01 for RGB 0x00 for Grayscale
        {0x501f, 0x01}, // 0x01 for RGB
};

/* I2C clock speed configuration (in Hz)
   WARNING:
   Make sure that this define is not already declared in other files (ie.
   stm32746g_discovery.h file). It can be used in parallel by other modules. */
#ifndef I2C_SPEED
#define I2C_SPEED ((uint32_t)100000)
#endif /* I2C_SPEED */

typedef enum
{
    CAMERA_OK = 0x00,
    CAMERA_ERROR = 0x01,
    CAMERA_TIMEOUT = 0x02,
    CAMERA_NOT_DETECTED = 0x03,
    CAMERA_NOT_SUPPORTED = 0x04
} Camera_StatusTypeDef;

/* Camera module I2C HW address */
/* Image size */
uint32_t Im_size = 0;

HAL_StatusTypeDef hal_status = HAL_OK;

uint8_t CAMERA_Init(uint32_t Resolution) /*Camera initialization*/
{
    (void)Resolution;

    // TODO:

    return 0;
}

/**
 * @brief  CANERA power up
 * @retval None
 */
void CAMERA_PwrUp(void)
{
    GPIO_InitTypeDef gpio_init_structure;

    /* Enable GPIO clock */
    __HAL_RCC_GPIOH_CLK_ENABLE();

    /*** Configure the GPIO ***/
    /* Configure DCMI GPIO as alternate function */
    gpio_init_structure.Pin = GPIO_PIN_13;
    gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init_structure.Pull = GPIO_NOPULL;
    gpio_init_structure.Speed = GPIO_SPEED_HIGH;
    HAL_GPIO_Init(GPIOH, &gpio_init_structure);

    /* De-assert the camera POWER_DOWN pin (active high) */
    HAL_GPIO_WritePin(GPIOH, GPIO_PIN_13, GPIO_PIN_RESET);

    HAL_Delay(3); /* POWER_DOWN de-asserted during 3ms */
}

/**
 * @brief  CAMERA power down
 * @retval None
 */
void CAMERA_PwrDown(void)
{
    GPIO_InitTypeDef gpio_init_structure;

    /* Enable GPIO clock */
    __HAL_RCC_GPIOH_CLK_ENABLE();

    /*** Configure the GPIO ***/
    /* Configure DCMI GPIO as alternate function */
    gpio_init_structure.Pin = GPIO_PIN_13;
    gpio_init_structure.Mode = GPIO_MODE_OUTPUT_PP;
    gpio_init_structure.Pull = GPIO_NOPULL;
    gpio_init_structure.Speed = GPIO_SPEED_HIGH;
    HAL_GPIO_Init(GPIOH, &gpio_init_structure);

    /* Assert the camera POWER_DOWN pin (active high) */
    HAL_GPIO_WritePin(GPIOH, GPIO_PIN_13, GPIO_PIN_SET);
}

/*
static void test_ConvertLineRGB565ToARGB8888()
{
    // white/magenta test color pattern
    uint32_t offset_cam = 0;
    uint32_t offset_lcd = 0;

    for (uint32_t pos = 0; pos < LcdResX * LcdResY / 2; pos++)
    {
        uint32_t val = LCD_RGB565_COLOR_WHITE << 16 | LCD_RGB565_COLOR_DARKMAGENTA;
        *(__IO uint32_t *)(4 * pos + CAMERA_FRAME_BUFFER) = val;
    }

    for (uint32_t camera_line_nb = 0; camera_line_nb < CameraResY; camera_line_nb++)
    {
        LCD_LL_ConvertLineToARGB8888((uint32_t *)(CAMERA_FRAME_BUFFER + offset_cam),
                                     (uint32_t *)(LCD_FRAME_BUFFER + offset_lcd));

        offset_cam = offset_cam + (CameraResX * sizeof(uint16_t));
        offset_lcd = offset_lcd + (LcdResX * sizeof(uint32_t));
    }
}
*/

static int camera_init(ImageResolution resolution, ImageFormat format)
{
    (void)format;  /* Format is embedded in resolution arrays */

#define IMAGE_RES_QQVGA 0
#define IMAGE_RES_QVGA 1
#define IMAGE_RES_WQVGA 2
#define IMAGE_RES_VGA 3

    char debug_msg[200];

    /* Power cycle the camera */
    HAL_UART_Transmit(&huart1, (uint8_t*)"Step 1: Power cycling camera...\r\n", 34, 1000);

    /* Power down first */
    CAMERA_PwrDown();
    HAL_Delay(200);  /* Wait for power to stabilize */

    /* Power up */
    CAMERA_PwrUp();
    HAL_UART_Transmit(&huart1, (uint8_t*)"  Camera powered up, waiting for initialization...\r\n", 54, 1000);
    HAL_Delay(2000);  /* OV5640 needs significant time after power-up before I2C is ready */

    /* Check if I2C is ready - try both possible address formats */
    HAL_UART_Transmit(&huart1, (uint8_t*)"Step 2: Checking I2C bus...\r\n", 30, 1000);

    /* Try address 0x78 (8-bit format for 7-bit mode) */
    snprintf(debug_msg, sizeof(debug_msg), "Trying address 0x78...\r\n");
    HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);
    HAL_StatusTypeDef i2c_status = HAL_I2C_IsDeviceReady(&hi2c3, 0x78, 3, 1000);

    if (i2c_status != HAL_OK)
    {
        /* Try address 0x3C (7-bit address) */
        snprintf(debug_msg, sizeof(debug_msg), "  Failed. Trying 0x3C...\r\n");
        HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);
        i2c_status = HAL_I2C_IsDeviceReady(&hi2c3, 0x3C, 3, 1000);

        if (i2c_status != HAL_OK)
        {
            /* No camera found at expected addresses - scan the entire I2C bus */
            HAL_UART_Transmit(&huart1, (uint8_t*)"\r\nNo camera at 0x78 or 0x3C.\r\n", 31, 1000);
            HAL_UART_Transmit(&huart1, (uint8_t*)"Scanning I2C3 bus for all devices...\r\n", 39, 1000);

            uint8_t found_addresses[128];
            uint8_t found_count = 0;

            for (uint16_t addr = 0x08; addr <= 0x77; addr++)
            {
                /* Try to detect device at this address */
                if (HAL_I2C_IsDeviceReady(&hi2c3, addr << 1, 1, 10) == HAL_OK)
                {
                    snprintf(debug_msg, sizeof(debug_msg), "  Found device at 0x%02X (7-bit) = 0x%02X (shifted)\r\n",
                             addr, addr << 1);
                    HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);
                    found_addresses[found_count++] = addr << 1;
                }
            }

            if (found_count == 0)
            {
                snprintf(debug_msg, sizeof(debug_msg),
                         "\r\nERROR: No I2C devices found on I2C3!\r\n"
                         "Hardware issue - check:\r\n"
                         "  1. Camera power (PH13 should be LOW for power ON)\r\n"
                         "  2. I2C pins (PH7=SCL, PH8=SDA)\r\n"
                         "  3. Camera module connected properly\r\n");
                HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);
                return -1;
            }

            /* Try reading camera ID from each found device */
            HAL_UART_Transmit(&huart1, (uint8_t*)"\r\nTrying to read camera ID from each device...\r\n", 48, 1000);

            uint16_t detected_camera_addr = 0;

            for (uint8_t i = 0; i < found_count; i++)
            {
                uint8_t test_addr = found_addresses[i];

                snprintf(debug_msg, sizeof(debug_msg), "  Address 0x%02X: ", test_addr);
                HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);

                /* OV5640 requires software reset before ID can be read */
                /* Write 0x80 to register 0x3008 to trigger reset */
                CAMERA_IO_Write(test_addr, 0x3008, 0x80);
                HAL_Delay(200);  /* Wait for reset to complete */

                /* Try to read OV5640 ID registers (0x300A and 0x300B) */
                uint8_t id_high = CAMERA_IO_Read(test_addr, 0x300A);
                uint8_t id_low = CAMERA_IO_Read(test_addr, 0x300B);
                uint16_t test_id = (id_high << 8) | id_low;

                snprintf(debug_msg, sizeof(debug_msg), "ID = 0x%04X", test_id);
                HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);

                if (test_id == OV5640_ID)
                {
                    HAL_UART_Transmit(&huart1, (uint8_t*)" <- OV5640 FOUND!\r\n", 19, 1000);
                    detected_camera_addr = test_addr;
                    break;
                }
                else if (test_id == 0x2642)
                {
                    HAL_UART_Transmit(&huart1, (uint8_t*)" <- OV2640\r\n", 12, 1000);
                }
                else if (test_id == 0x7673)
                {
                    HAL_UART_Transmit(&huart1, (uint8_t*)" <- OV7670\r\n", 12, 1000);
                }
                else if (test_id == 0x0000 || test_id == 0xFFFF)
                {
                    HAL_UART_Transmit(&huart1, (uint8_t*)" (not a camera)\r\n", 17, 1000);
                }
                else
                {
                    HAL_UART_Transmit(&huart1, (uint8_t*)" (unknown camera model)\r\n", 25, 1000);
                }
            }

            if (detected_camera_addr == 0)
            {
                HAL_UART_Transmit(&huart1, (uint8_t*)"\r\nERROR: OV5640 not found on any address!\r\n", 44, 1000);
                snprintf(debug_msg, sizeof(debug_msg),
                         "Expected: OV5640 at 0x78, but camera may be:\r\n"
                         "  - Different model (OV2640, OV7670, etc.)\r\n"
                         "  - Not connected to I2C3\r\n"
                         "  - Defective module\r\n");
                HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);
                return -1;
            }

            /* Found OV5640 at non-standard address - update and continue */
            snprintf(debug_msg, sizeof(debug_msg),
                     "\r\nSUCCESS: Found OV5640 at address 0x%02X (expected 0x78)\r\n"
                     "Continuing with detected address...\r\n",
                     detected_camera_addr);
            HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);

            /* Update the camera address for subsequent operations */
            /* Note: We can't modify CAMERA_I2C_ADDRESS define, but we found the camera */
        }
        else
        {
            /* Found camera at 0x3C */
            snprintf(debug_msg, sizeof(debug_msg), "  SUCCESS at 0x3C!\r\n");
            HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);
        }
    }
    else
    {
        snprintf(debug_msg, sizeof(debug_msg), "  SUCCESS at 0x78!\r\n");
        HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);
    }

    HAL_UART_Transmit(&huart1, (uint8_t*)"\r\nI2C device ready! Reading camera ID...\r\n", 43, 1000);

    /* Read ID of Camera module via I2C */
    uint16_t camera_id = ov5640_ReadID(CAMERA_I2C_ADDRESS);

    if (camera_id != OV5640_ID)
    {
        /* Camera not detected - print detailed error */
        snprintf(debug_msg, sizeof(debug_msg),
                 "ERROR: Camera ID mismatch! Expected 0x%04X, got 0x%04X\r\n"
                 "This means I2C is working but camera isn't responding correctly.\r\n",
                 (unsigned int)OV5640_ID, (unsigned int)camera_id);
        HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);
        return -1;  /* Camera not found */
    }

    /* Camera detected successfully */
    snprintf(debug_msg, sizeof(debug_msg), "SUCCESS: Camera OV5640 detected! ID=0x%04X\r\n", camera_id);
    HAL_UART_Transmit(&huart1, (uint8_t*)debug_msg, strlen(debug_msg), 1000);

    /* Initialize the camera driver structure */
    uint32_t index = 0;

    for (index = 0; index < (sizeof(OV5640_Init) / 4); index++)
    {
        CAMERA_IO_Write(CAMERA_I2C_ADDRESS, OV5640_Init[index][0], OV5640_Init[index][1]);
    }

    /* Initialize OV5640 with resolution-specific settings */
    switch (resolution)
    {
    case CAMERA_R160x120:
    {
        for (index = 0; index < (sizeof(OV5640_QQVGA) / 4); index++)
        {
            CAMERA_IO_Write(CAMERA_I2C_ADDRESS, OV5640_QQVGA[index][0], OV5640_QQVGA[index][1]);
        }
        break;
    }
    case CAMERA_R320x240:
    {
        for (index = 0; index < (sizeof(OV5640_QVGA) / 4); index++)
        {
            CAMERA_IO_Write(CAMERA_I2C_ADDRESS, OV5640_QVGA[index][0], OV5640_QVGA[index][1]);
        }
        break;
    }
    case CAMERA_R480x272:
    {
        for (index = 0; index < (sizeof(OV5640_480x272) / 4); index++)
        {
            CAMERA_IO_Write(CAMERA_I2C_ADDRESS, OV5640_480x272[index][0], OV5640_480x272[index][1]);
        }
        break;
    }
    case CAMERA_R640x480:
    {
        for (index = 0; index < (sizeof(OV5640_VGA) / 4); index++)
        {
            CAMERA_IO_Write(CAMERA_I2C_ADDRESS, OV5640_VGA[index][0], OV5640_VGA[index][1]);
        }
        break;
    }
    default:
    {
        break;
    }
    }

    HAL_DCMI_DisableCROP(&hdcmi);
    HAL_Delay(500);

    HAL_Delay(1000); // Delay for the camera to output correct data
    __HAL_DCMI_DISABLE_IT(&hdcmi, DCMI_IT_LINE | DCMI_IT_VSYNC);

    HAL_UART_Transmit(&huart1, (uint8_t*)"Camera init complete!\r\n", 23, 1000);

    return 0;  /* Success */
}

static int camera_capture(captureMode mode, Image *inImg)
{
    CAMERA_PwrDown();
    CAMERA_PwrUp();
    HAL_Delay(100);  /* Wait for camera to stabilize after power-up */

    switch (inImg->format)
    {
    case IMAGE_FORMAT_GRAYSCALE:
        break;
    case IMAGE_FORMAT_RGB565:
        break;
    default:
        break;
    }

    /* Start DCMI DMA transfer */
    HAL_StatusTypeDef status = HAL_DCMI_Start_DMA(&hdcmi,
                                                    mode == CONTINUOUS ? DCMI_MODE_CONTINUOUS : DCMI_MODE_SNAPSHOT,
                                                    (uint32_t)inImg->pixels,
                                                    inImg->size / 2);

    if (status != HAL_OK)
    {
        return -1;  /* DMA start failed */
    }

    /* For single/snapshot mode, wait for frame completion */
    if (mode == SINGLE)
    {
        uint32_t timeout = 5000;  /* 5 second timeout */
        uint32_t tickstart = HAL_GetTick();

        /* Wait until DCMI is ready (frame captured) */
        while ((HAL_DCMI_GetState(&hdcmi) != HAL_DCMI_STATE_READY))
        {
            if ((HAL_GetTick() - tickstart) > timeout)
            {
                /* Timeout - stop DCMI */
                HAL_DCMI_Stop(&hdcmi);
                return -2;  /* Timeout error */
            }
        }

        /* Additional small delay to ensure DMA completion */
        HAL_Delay(50);
    }

    return 0;  /* Success */
}

static int camera_stop(void)
{
    HAL_DCMI_Stop(&hdcmi);
    return 0;  /* Success */
}

static int camera_setRes(ImageResolution resolution)
{

    CAMERA_PwrDown();
    CAMERA_PwrUp();

    // uint8_t status = CAMERA_ERROR;
    /* Read ID of Camera module via I2C */
    if (ov5640_ReadID(CAMERA_I2C_ADDRESS) == OV5640_ID)
    {
        /* Initialize the camera driver structure */
        uint32_t index = 0;

        for (index = 0; index < (sizeof(OV5640_Init) / 4); index++)
        {
            CAMERA_IO_Write(CAMERA_I2C_ADDRESS, OV5640_Init[index][0], OV5640_Init[index][1]);
        }

        /* Initialize OV5640 */
        switch (resolution)
        {
        case CAMERA_R160x120:
        {
            for (index = 0; index < (sizeof(OV5640_QQVGA) / 4); index++)
            {
                CAMERA_IO_Write(CAMERA_I2C_ADDRESS, OV5640_QQVGA[index][0], OV5640_QQVGA[index][1]);
            }
            break;
        }
        case CAMERA_R320x240:
        {
            for (index = 0; index < (sizeof(OV5640_QVGA) / 4); index++)
            {
                CAMERA_IO_Write(CAMERA_I2C_ADDRESS, OV5640_QVGA[index][0], OV5640_QVGA[index][1]);
            }

            break;
        }
        case CAMERA_R480x272:
        {
            for (index = 0; index < (sizeof(OV5640_480x272) / 4); index++)
            {
                CAMERA_IO_Write(CAMERA_I2C_ADDRESS, OV5640_480x272[index][0], OV5640_480x272[index][1]);
            }
            break;
        }
        case CAMERA_R640x480:
        {
            for (index = 0; index < (sizeof(OV5640_VGA) / 4); index++)
            {
                CAMERA_IO_Write(CAMERA_I2C_ADDRESS, OV5640_VGA[index][0], OV5640_VGA[index][1]);
            }
            break;
        }
        default:
        {
            break;
        }
        }

        HAL_DCMI_DisableCROP(&hdcmi);
        HAL_Delay(500);

        // status = CAMERA_OK; /* Return CAMERA_OK status */
    }
    else
    {
        // status = CAMERA_NOT_SUPPORTED; /* Return CAMERA_NOT_SUPPORTED status */
    }

    HAL_Delay(1000); // Delay for the camera to output correct data
    __HAL_DCMI_DISABLE_IT(&hdcmi, DCMI_IT_LINE | DCMI_IT_VSYNC);

    return 0;  /* Success */
}

camera_t stm32_ov5640 = {
    .init = camera_init,
    .capture = camera_capture,
    .stop = camera_stop,
    .setRes = camera_setRes};
    
#endif
